import assert from "node:assert/strict";
import test from "node:test";
import { canonicalJson, canonicalJsonDigest } from "../src/content-digest.mjs";
import { evaluateArchitectureDiscoveryGapPolicy, ArchitectureDiscoveryGapPolicyError } from "../src/architecture-discovery-gap-policy.mjs";
import { createArchitectureDiscoveryCheckpointController, ArchitectureDiscoveryCheckpointError } from "../src/architecture-discovery-checkpoint.mjs";

const D=(ch)=>`sha256:${ch.repeat(64)}`;
const seal=(body,field)=>({...body,[field]:canonicalJsonDigest(Object.fromEntries(Object.entries(body).filter(([key])=>!["apiVersion","kind",field].includes(key))))});
const repository={artifactId:"repository",digest:D("a")};
const adapter={id:"native",version:"0.1.0",configurationDigest:D("b")};
const source={artifact:{artifactId:"source",digest:D("c")},location:{path:"src/index.mjs"}};
const observation=(id,subject,statement,score=1,disposition="observed")=>seal({apiVersion:"devrelay.dev/v1alpha1",kind:"ArchitectureObservation",observationId:id,repositorySnapshot:repository,finding:{id:`F-${id}`,category:"element",subject,statement,confidence:{disposition,score,rationale:"Exact normalized fixture evidence."},method:disposition==="observed"?"native-inventory":"specialized-analyzer",adapter,sources:[source]}},"observationDigest");
const observationRef=(value)=>({artifactId:value.observationId,digest:value.observationDigest});
function snapshot(observations) { return seal({apiVersion:"devrelay.dev/v1alpha1",kind:"CurrentArchitectureSnapshot",snapshotId:"SNAP",repositorySnapshot:repository,nativeInventory:{artifactId:"inventory",digest:D("d")},analyzerResults:[],observations:observations.map(observationRef),gaps:[],warnings:[],discoveryMethods:["native-inventory"],sourceRefs:[source],authority:"observational"},"snapshotDigest"); }
const rule=(id,subject,condition,material,extra={})=>({id,subject,condition,material,reason:`${condition} evidence for ${subject} requires explicit review.`,sources:[source],...extra});

test("complete evidence produces a deterministic discovered snapshot",()=>{const values=[observation("OBS-A","service:a","Service A exists.")];const first=evaluateArchitectureDiscoveryGapPolicy({snapshot:snapshot(values),observations:values,rules:[rule("R","service:a","missing",true)]});const second=evaluateArchitectureDiscoveryGapPolicy({snapshot:snapshot(values),observations:[...values].reverse(),rules:[rule("R","service:a","missing",true)]});assert.equal(first.outcome,"discovered");assert.equal(first.gaps.length,0);assert.equal(canonicalJson(first.snapshot),canonicalJson(second.snapshot))});
test("material missing and conflicting facts require clarification",()=>{for(const [values,rules] of [[[observation("OBS-OTHER","service:other","Another service exists.")],[rule("M","service:missing","missing",true)]],[[observation("OBS-A","service:a","A uses SQL."),observation("OBS-B","service:a","A uses files.")],[rule("C","service:a","conflict",true)]]]){const result=evaluateArchitectureDiscoveryGapPolicy({snapshot:snapshot(values),observations:values,rules});assert.equal(result.outcome,"needs_clarification");assert.equal(result.gaps[0].material,true);assert.equal("snapshot" in result,false)}});
test("documented non-material low confidence proceeds without losing uncertainty",()=>{const values=[observation("OBS-L","service:a","Service A may exist.",0.4,"analyzer-inferred")];const result=evaluateArchitectureDiscoveryGapPolicy({snapshot:snapshot(values),observations:values,rules:[rule("LOW","service:a","low-confidence",false,{minimumScore:0.8})]});assert.equal(result.outcome,"discovered");assert.equal(result.gaps[0].material,false);assert.equal(result.snapshot.gaps[0].digest,result.gaps[0].gapDigest);assert.match(result.snapshot.warnings[0],/Non-material discovery gap/)});
test("materiality belongs only to explicit Core policy",()=>{const values=[observation("OBS-L","service:a","Maybe.",0.1,"unknown")];assert.throws(()=>evaluateArchitectureDiscoveryGapPolicy({snapshot:snapshot(values),observations:values,rules:[{...rule("LOW","service:a","low-confidence",false,{minimumScore:0.8}),material:undefined}]}),ArchitectureDiscoveryGapPolicyError)});

const inventoryInvocation=(id="INV")=>seal({apiVersion:"devrelay.dev/v1alpha1",kind:"RepositoryInventoryInvocation",invocationId:id,repositorySnapshot:repository,allowedPaths:["src/index.mjs"],policy:{artifactId:"policy",digest:D("e")},adapter},"invocationFingerprint");
const inventoryResult=(inv)=>seal({apiVersion:"devrelay.dev/v1alpha1",kind:"NativeRepositoryInventory",invocationId:inv.invocationId,invocationFingerprint:inv.invocationFingerprint,repositorySnapshot:repository,adapter,status:"completed",findings:[],nativeEvidence:[{artifactId:"evidence",digest:D("f")}]},"inventoryDigest");
function store(){const values=new Map();return {values,async get(key){return values.get(key)},async put(key,value){if(values.has(key))throw new Error("overwrite");values.set(key,structuredClone(value))}}}

test("exact durable checkpoint replay is byte-identical and invokes the adapter zero times",async()=>{let calls=0;const invocation=inventoryInvocation(),result=inventoryResult(invocation),bytes=Buffer.from(canonicalJson(result));const checkpoints=store();const controller=createArchitectureDiscoveryCheckpointController({adapter:async()=>{calls++;return bytes}});const first=await controller.execute({invocation,checkpoints});const replay=await controller.execute({invocation,checkpoints});assert.equal(calls,1);assert.equal(replay.replayed,true);assert.equal(replay.adapterCalls,0);assert.equal(replay.checkpointDigest,first.checkpointDigest);assert.deepEqual(Buffer.from(replay.nativeBytes),bytes)});
test("stale invocation and substituted checkpoint fail closed without another call",async()=>{let calls=0;const invocation=inventoryInvocation();const checkpoints=store();const controller=createArchitectureDiscoveryCheckpointController({adapter:async()=>{calls++;return inventoryResult(invocation)}});await controller.execute({invocation,checkpoints});const stale=seal({...invocation,repositorySnapshot:{...repository,digest:D("0")}},"invocationFingerprint");await assert.rejects(controller.execute({invocation:stale,checkpoints}),ArchitectureDiscoveryCheckpointError);const [key,saved]=[...checkpoints.values.entries()][0];saved.checkpoint.result.digest=D("1");checkpoints.values.set(key,saved);await assert.rejects(controller.execute({invocation,checkpoints}),ArchitectureDiscoveryCheckpointError);assert.equal(calls,1)});
test("changed invocation identity receives a distinct checkpoint and result",async()=>{let calls=0;const checkpoints=store();const controller=createArchitectureDiscoveryCheckpointController({adapter:async inv=>{calls++;return inventoryResult(inv)}});await controller.execute({invocation:inventoryInvocation("INV-1"),checkpoints});await controller.execute({invocation:inventoryInvocation("INV-2"),checkpoints});assert.equal(calls,2);assert.equal(checkpoints.values.size,2)});
