import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { canonicalJson, canonicalJsonDigest, sha256Digest } from "../src/content-digest.mjs";
import { deriveBusinessAcceptanceTechnicalCoverage, deriveBusinessScopeIdentities, executeBusinessAcceptance } from "../src/business-acceptance-core.mjs";
import { createInMemoryTraceabilityStore, createTraceabilityGraphService } from "../src/traceability-graph.mjs";

const API="devrelay.dev/v1alpha1", D=`sha256:${"1".repeat(64)}`;
const ref=(artifactId,digest=D)=>({artifactId,digest});
const seal=(body,field)=>({...body,[field]:canonicalJsonDigest(Object.fromEntries(Object.entries(body).filter(([key])=>!["apiVersion","kind",field].includes(key))))});
const scopeRecord=(id,statement)=>({id,statement,sourceRefs:[{role:"requirements-baseline",artifact:ref("REQ-SOURCE")}]});
const requirementsValue={apiVersion:API,kind:"RequirementsBaseline",baselineId:"REQ",requirements:{businessObjectives:[{id:"BO-1"}],successMetrics:[{id:"SM-1"}],acceptanceCriteria:[{id:"AC-1"},{id:"AC-2"}],scope:[scopeRecord("SCOPE-Z","Zulu scope"),scopeRecord("SCOPE-A","Alpha scope")]}};
const requirementsBytes=Buffer.from(JSON.stringify(requirementsValue,null,2));
const requirementsBaseline={value:requirementsValue,bytes:requirementsBytes,ref:ref("REQ",sha256Digest(requirementsBytes))};
const projectOverviewBaseline=ref("OVERVIEW"),architectureBaseline=ref("ARCH"),contractDisposition=ref("CONTRACT");
const policy=seal({apiVersion:API,kind:"BusinessAcceptancePolicy",policyId:"BA-POL",version:"1.0.0",allObjectivesMandatory:true,allMetricsMandatory:true,allBusinessScopeMandatory:true,allAcceptanceCriteriaMandatory:true,unknownEvidence:"reject",outcomePrecedence:["failed","needs-evidence","satisfied"]},"policyDigest");
const integratedSystemCandidate=seal({apiVersion:API,kind:"IntegratedSystemCandidate",subjectId:"SYSTEM-1",repositorySnapshot:ref("REPO"),integratedChangeRecords:[ref("CHANGE")],integratedCompletionFactSet:ref("FACTS"),requirementsBaseline:requirementsBaseline.ref,projectOverviewBaseline,architectureBaseline,contractDisposition,workBreakdownBaseline:ref("WORK"),workDependencyBaseline:ref("DAG"),specialistAssignmentBaseline:ref("ASSIGN"),verificationEnvironment:ref("ENV"),systemVerificationPolicy:ref("SV-POLICY")},"subjectDigest");
const systemVerificationResult=seal({apiVersion:API,kind:"SystemVerificationResult",resultId:"SVR",subject:ref(integratedSystemCandidate.subjectId,integratedSystemCandidate.subjectDigest),obligationSet:ref("SV-OBLIGATIONS"),policy:ref("SV-POLICY"),evidence:ref("SV-EVIDENCE"),evaluation:ref("SV-EVALUATION"),outcome:"verified",progression:"business-acceptance-gate",authority:"system-verification"},"resultDigest");
const resultRef=ref(systemVerificationResult.resultId,systemVerificationResult.resultDigest);
const sourceRef={...requirementsBaseline.ref,schema:"https://devrelay.dev/test/requirements/v1",mediaType:"application/json",uri:"memory://requirements.json"};
const source={value:requirementsValue,bytes:requirementsBytes,ref:sourceRef};
const coverageContributor={metadata:{id:"fixture.business-acceptance-coverage",version:"1.0.0"},authority:"approved",scope:"system-verification/approved",ownership:{authority:"approved",scope:"system-verification/approved",nodeKinds:["acceptance-criterion","test","verification-evidence"],edgeKinds:["tested-by","produces","verified-by"]},match:()=>true,project:()=>({horizon:"verification",nodes:[
  {kind:"acceptance-criterion",stableId:"AC-1",label:"AC-1",attributes:{},sourceLocators:[{artifact:requirementsBaseline.ref,jsonPointer:"/requirements/acceptanceCriteria/0",entityDigest:canonicalJsonDigest(requirementsValue.requirements.acceptanceCriteria[0])}]},
  {kind:"acceptance-criterion",stableId:"AC-2",label:"AC-2",attributes:{},sourceLocators:[{artifact:requirementsBaseline.ref,jsonPointer:"/requirements/acceptanceCriteria/1",entityDigest:canonicalJsonDigest(requirementsValue.requirements.acceptanceCriteria[1])}]},
  {kind:"test",stableId:"TEST",label:"TEST",attributes:{},sourceLocators:[{artifact:requirementsBaseline.ref,jsonPointer:"",entityDigest:canonicalJsonDigest(requirementsValue)}]},
  {kind:"verification-evidence",stableId:"EV-1",label:"EV-1",verificationStatus:"pass",attributes:{artifact:ref("REPORT-1"),systemVerificationResult:resultRef},sourceLocators:[{artifact:requirementsBaseline.ref,jsonPointer:"",entityDigest:canonicalJsonDigest(requirementsValue)}]},
  {kind:"verification-evidence",stableId:"EV-2",label:"EV-2",verificationStatus:"pass",attributes:{artifact:ref("REPORT-2"),systemVerificationResult:resultRef},sourceLocators:[{artifact:requirementsBaseline.ref,jsonPointer:"",entityDigest:canonicalJsonDigest(requirementsValue)}]}
],edges:[
  {kind:"tested-by",source:{kind:"acceptance-criterion",stableId:"AC-1"},target:{kind:"test",stableId:"TEST"},rationale:"Criterion is tested.",sourceLocators:[{artifact:requirementsBaseline.ref,jsonPointer:"",entityDigest:canonicalJsonDigest(requirementsValue)}]},
  {kind:"produces",source:{kind:"test",stableId:"TEST"},target:{kind:"verification-evidence",stableId:"EV-1"},rationale:"Test produces evidence.",sourceLocators:[{artifact:requirementsBaseline.ref,jsonPointer:"",entityDigest:canonicalJsonDigest(requirementsValue)}]},
  {kind:"verified-by",source:{kind:"acceptance-criterion",stableId:"AC-2"},target:{kind:"verification-evidence",stableId:"EV-2"},rationale:"Criterion is verified.",sourceLocators:[{artifact:requirementsBaseline.ref,jsonPointer:"",entityDigest:canonicalJsonDigest(requirementsValue)}]}
]})};
const graphService=createTraceabilityGraphService({graphId:"business-acceptance-coverage",projectId:"devrelay",store:createInMemoryTraceabilityStore(),contributors:[coverageContributor]});
const invocation={invocationId:"coverage-fixture",module:{id:"fixture",version:"1.0.0",operation:"project"}};
const moduleResult={apiVersion:API,kind:"ModuleResult",invocationId:invocation.invocationId,status:"completed",outcome:"verified",outputs:{fixture:[sourceRef]},evidence:[],diagnostics:[]};
const prepared=await graphService.prepare({baseGraph:graphService.captureBase(),invocation,invocationFingerprint:D,moduleResult,loadedInputs:{},loadedOutputs:{fixture:[source]}});
await graphService.mergePrepared(prepared);
const captured=graphService.captureBase();
const graph={value:captured.snapshot,bytes:captured.bytes,ref:captured.ref};
const graphCheckpoint=ref(graph.ref.artifactId,graph.ref.digest);
const graphValue=graph.value;
const scopeIds=deriveBusinessScopeIdentities(requirementsBaseline).map(x=>x.scopeId);
const evidenceFor=(statuses=["pass","pass","pass","pass"])=>seal({apiVersion:API,kind:"BusinessAcceptanceEvidenceSet",evidenceSetId:`EV-${statuses.join("-")}`,requirementsBaseline:requirementsBaseline.ref,projectOverviewBaseline,systemVerificationResult:resultRef,items:[
  {evidenceId:"E-BO",scopeKind:"business-objective",scopeId:"BO-1",status:statuses[0],artifact:ref("REPORT-BO"),producer:{id:"owner",version:"1.0.0"}},
  {evidenceId:"E-SM",scopeKind:"success-metric",scopeId:"SM-1",status:statuses[1],artifact:ref("REPORT-SM"),producer:{id:"owner",version:"1.0.0"}},
  ...scopeIds.map((scopeId,index)=>({evidenceId:`E-BS-${index}`,scopeKind:"business-scope",scopeId,status:statuses[index+2],artifact:ref(`REPORT-BS-${index}`),producer:{id:"owner",version:"1.0.0"}}))
]},"evidenceDigest");
const store=()=>{const values=new Map();return{get:key=>values.get(key),put:(key,value)=>{if(values.has(key))throw new Error("immutable");values.set(key,structuredClone(value))}}};
const input=evidence=>({integratedSystemCandidate,systemVerificationResult,requirementsBaseline:requirementsBaseline.ref,projectOverviewBaseline,architectureBaseline,contractDisposition,repositoryReleaseSnapshot:ref("RELEASE"),traceabilityCheckpoint:graphCheckpoint,policy,evidence});

test("derives exhaustive exact technical coverage from approved forward topology",()=>{const coverage=deriveBusinessAcceptanceTechnicalCoverage({requirementsBaseline,systemVerificationResult,traceabilityGraphSnapshot:graph,traceabilityCheckpoint:graph.ref});assert.deepEqual(coverage.approvedAcceptanceCriterionIds,["AC-1","AC-2"]);for(const entry of coverage.entries){const pathEdges=entry.pathEdgeIds.map(id=>graphValue.edges.find(edge=>edge.edgeId===id));assert.ok(pathEdges.every(Boolean));assert.equal(entry.pathNodeIds[0],graphValue.nodes.find(node=>node.kind==="acceptance-criterion"&&node.stableId===entry.acceptanceCriterionId).nodeId);assert.equal(entry.pathNodeIds.at(-1),entry.evidenceNodeId);pathEdges.forEach((edge,index)=>assert.deepEqual([edge.sourceNodeId,edge.targetNodeId],[entry.pathNodeIds[index],entry.pathNodeIds[index+1]]))}assert.deepEqual(coverage.entries.map(x=>x.evidence.artifactId),["REPORT-1","REPORT-2"])});

test("technical coverage rejects malformed envelopes, raw-byte drift, parsed-value substitution, and checkpoint drift",()=>{const changedBytes=Buffer.from(graph.bytes);changedBytes[changedBytes.length-2]^=1;for(const changed of [{...graph,bytes:changedBytes},{...graph,value:{...graph.value,projectId:"other"}},{value:{apiVersion:API,kind:"TraceabilityGraphSnapshot",nodes:[],edges:[]},bytes:Buffer.from("{}"),ref:ref("GRAPH",sha256Digest(Buffer.from("{}")))}])assert.throws(()=>deriveBusinessAcceptanceTechnicalCoverage({requirementsBaseline,systemVerificationResult,traceabilityGraphSnapshot:changed}),error=>error.outcome==="baseline-drift");assert.throws(()=>deriveBusinessAcceptanceTechnicalCoverage({requirementsBaseline,systemVerificationResult,traceabilityGraphSnapshot:graph,traceabilityCheckpoint:ref("OTHER")}),error=>error.outcome==="baseline-drift")});

test("raw-byte RequirementsBaseline accepts pretty JSON and rejects byte/value/ref substitutions",()=>{assert.doesNotThrow(()=>deriveBusinessAcceptanceTechnicalCoverage({requirementsBaseline,systemVerificationResult,traceabilityGraphSnapshot:graph}));const canonicalBytes=Buffer.from(canonicalJson(requirementsValue));assert.notEqual(sha256Digest(canonicalBytes),requirementsBaseline.ref.digest);for(const changed of [{...requirementsBaseline,bytes:canonicalBytes},{...requirementsBaseline,value:{...requirementsValue,baselineId:"OTHER"}},{...requirementsBaseline,ref:ref("REQ",D)}])assert.throws(()=>deriveBusinessAcceptanceTechnicalCoverage({requirementsBaseline:changed,systemVerificationResult,traceabilityGraphSnapshot:graph}),error=>error.outcome==="baseline-drift")});

test("business scope preserves approved identities and provenance in code-unit order",()=>{const scopes=deriveBusinessScopeIdentities(requirementsBaseline);assert.deepEqual(scopes.map(x=>[x.scopeId,x.statement]),[["SCOPE-A","Alpha scope"],["SCOPE-Z","Zulu scope"]]);assert.deepEqual(scopes[0].sourceRefs,requirementsValue.requirements.scope[1].sourceRefs);const malformed=[[scopeRecord("","statement")],[scopeRecord("SCOPE-A"," ")],[scopeRecord("SCOPE-A","same"),scopeRecord("SCOPE-A","other")],[scopeRecord("SCOPE-A","same"),scopeRecord("SCOPE-B","same")],[{id:"SCOPE-A",statement:"statement",sourceRefs:[]}],[{...scopeRecord("SCOPE-A","statement"),extra:true}]];for(const scope of malformed)assert.throws(()=>deriveBusinessScopeIdentities({requirements:{scope}}),/exactly|non-empty|unique|provenance/)});

test("production RequirementsBaseline scope is returned exhaustively without identity or provenance loss",()=>{const production=JSON.parse(readFileSync(new URL("../project/requirements-baseline.json",import.meta.url),"utf8"));const expected=[...production.requirements.scope].sort((a,b)=>a.id<b.id?-1:a.id>b.id?1:0);const actual=deriveBusinessScopeIdentities(production);assert.equal(actual.length,expected.length);assert.deepEqual(actual,expected.map(({id,statement,sourceRefs})=>({scopeId:id,statement,sourceRefs})));assert.ok(actual.every(entry=>entry.scopeId.startsWith("SCOPE-")))});

test("evaluation covers objectives, metrics, and every derived business scope without technical execution",async()=>{const evidence=evidenceFor(),checkpoints=store();const coverage=deriveBusinessAcceptanceTechnicalCoverage({requirementsBaseline,systemVerificationResult,traceabilityGraphSnapshot:graph});const args={...input(evidence),requirementsBaseline:requirementsBaseline.ref,technicalCoverage:coverage,businessObjectiveIds:["BO-1"],successMetricIds:["SM-1"],businessScopeIds:scopeIds,checkpoints};const first=await executeBusinessAcceptance(args),second=await executeBusinessAcceptance(args);assert.equal(first.evaluation.outcome,"eligible-for-acceptance");assert.equal(first.evaluation.dispositions.length,4);assert.equal(first.replayed,false);assert.equal(second.replayed,true);assert.equal(second.evaluationCalls,0);assert.equal(second.evidenceCalls,0);assert.deepEqual(second.technicalCoverage,first.technicalCoverage);assert.deepEqual(second.candidate,first.candidate)});

test("execution derives and binds coverage directly from exact loaded baseline and graph bytes",async()=>{const evidence=evidenceFor(),resultBytes=Buffer.from(JSON.stringify(systemVerificationResult,null,2)),resultLoaded={value:systemVerificationResult,bytes:resultBytes,ref:ref("SVR-RAW",sha256Digest(resultBytes))};const executed=await executeBusinessAcceptance({...input(evidence),requirementsBaseline,systemVerificationResult:resultLoaded,traceabilityGraphSnapshot:graph,checkpoints:store()});assert.equal(executed.technicalCoverage.requirementsBaseline.digest,requirementsBaseline.ref.digest);assert.equal(executed.subject.systemVerificationResult.digest,systemVerificationResult.resultDigest);assert.equal(executed.evaluation.outcome,"eligible-for-acceptance")});

test("checkpoint replay rejects exact coverage substitution before evaluation",async()=>{const evidence=evidenceFor(),checkpoints=store(),coverage=deriveBusinessAcceptanceTechnicalCoverage({requirementsBaseline,systemVerificationResult,traceabilityGraphSnapshot:graph});const args={...input(evidence),technicalCoverage:coverage,businessObjectiveIds:["BO-1"],successMetricIds:["SM-1"],businessScopeIds:scopeIds,checkpoints};await executeBusinessAcceptance(args);const changed=seal({...coverage,entries:coverage.entries.map((entry,index)=>index?entry:{...entry,evidence:ref("OTHER")})},"coverageDigest");await assert.rejects(executeBusinessAcceptance({...args,technicalCoverage:changed}),/technical coverage|changed pinned context|subject/)});
