import assert from "node:assert/strict";
import test from "node:test";
import { canonicalJson, canonicalJsonDigest, sha256Digest } from "../src/content-digest.mjs";
import { executeBusinessAcceptanceGate, BusinessAcceptanceGateError } from "../src/business-acceptance-gate.mjs";

const API="devrelay.dev/v1alpha1", D=`sha256:${"a".repeat(64)}`, G=value=>`sha256:${value.repeat(64)}`, ref=(artifactId,digest=D)=>({artifactId,digest});
const seal=(value,field)=>({...value,[field]:canonicalJsonDigest(Object.fromEntries(Object.entries(value).filter(([key])=>!["apiVersion","kind",field].includes(key))))});
function fixture(outcome="eligible-for-acceptance") {
  const policy=seal({apiVersion:API,kind:"BusinessAcceptancePolicy",policyId:"POL",version:"1.0.0",allObjectivesMandatory:true,allMetricsMandatory:true,allBusinessScopeMandatory:true,allAcceptanceCriteriaMandatory:true,unknownEvidence:"reject",outcomePrecedence:["failed","needs-evidence","satisfied"]},"policyDigest");
  const integratedSystemCandidate={kind:"IntegratedSystemCandidate",subjectId:"ISC",subjectDigest:D,requirementsBaseline:ref("REQ"),projectOverviewBaseline:ref("PO"),architectureBaseline:ref("ARCH"),contractDisposition:ref("CD")};
  const systemVerificationResult={kind:"SystemVerificationResult",resultId:"SV",resultDigest:D,outcome:"verified",progression:"business-acceptance-gate",authority:"system-verification",subject:ref("ISC")};
  const technicalCoverage=seal({apiVersion:API,kind:"BusinessAcceptanceTechnicalCoverage",coverageId:"COVERAGE",requirementsBaseline:ref("REQ"),systemVerificationResult:ref("SV"),traceabilityCheckpoint:ref("TRACE"),approvedAcceptanceCriterionIds:["AC"],entries:[{acceptanceCriterionId:"AC",status:"passing",evidence:ref("SV-EVIDENCE"),evidenceNodeId:G("3"),pathNodeIds:[G("1"),G("3")],pathEdgeIds:[G("5")]}],technicalAuthority:"system-verification",derivationAuthority:"business-acceptance-core"},"coverageDigest");
  const evidence=seal({apiVersion:API,kind:"BusinessAcceptanceEvidenceSet",evidenceSetId:"EV",requirementsBaseline:ref("REQ"),projectOverviewBaseline:ref("PO"),systemVerificationResult:ref("SV"),items:[{evidenceId:"E1",scopeKind:"business-objective",scopeId:"BO",status:outcome==="rejected"?"fail":outcome==="needs-evidence"?"inconclusive":"pass",artifact:ref("A1"),producer:{id:"owner-evidence",version:"1.0.0"}},{evidenceId:"E2",scopeKind:"success-metric",scopeId:"SM",status:"pass",artifact:ref("A2"),producer:{id:"owner-evidence",version:"1.0.0"}},{evidenceId:"E3",scopeKind:"business-scope",scopeId:"BS",status:"pass",artifact:ref("A3"),producer:{id:"owner-evidence",version:"1.0.0"}}]},"evidenceDigest");
  const subject=seal({apiVersion:API,kind:"BusinessAcceptanceSubject",subjectId:"SUB",integratedSystemCandidate:ref("ISC"),systemVerificationResult:ref("SV"),technicalCoverage:ref(technicalCoverage.coverageId,technicalCoverage.coverageDigest),requirementsBaseline:ref("REQ"),projectOverviewBaseline:ref("PO"),architectureBaseline:ref("ARCH"),contractDisposition:ref("CD"),repositoryReleaseSnapshot:ref("REL"),policy:ref(policy.policyId,policy.policyDigest),businessEvidence:ref(evidence.evidenceSetId,evidence.evidenceDigest),traceabilityCheckpoint:ref("TRACE")},"subjectDigest");
  const dispositions=[{scopeKind:"business-objective",scopeId:"BO",status:outcome==="rejected"?"failed":outcome==="needs-evidence"?"needs-evidence":"satisfied",evidenceIds:["E1"]},{scopeKind:"success-metric",scopeId:"SM",status:"satisfied",evidenceIds:["E2"]},{scopeKind:"business-scope",scopeId:"BS",status:"satisfied",evidenceIds:["E3"]}];
  const evaluation=seal({apiVersion:API,kind:"BusinessAcceptanceEvaluation",evaluationId:"EVAL",subject:ref(subject.subjectId,subject.subjectDigest),policy:ref(policy.policyId,policy.policyDigest),evidence:ref(evidence.evidenceSetId,evidence.evidenceDigest),technicalCoverage:ref(technicalCoverage.coverageId,technicalCoverage.coverageDigest),approvedBusinessObjectiveIds:["BO"],approvedSuccessMetricIds:["SM"],approvedBusinessScopeIds:["BS"],dispositions,outcome},"evaluationDigest");
  const candidate=seal({apiVersion:API,kind:"BusinessAcceptanceCandidate",candidateId:"CAND",subject:evaluation.subject,policy:evaluation.policy,evidence:evaluation.evidence,evaluation:ref(evaluation.evaluationId,evaluation.evaluationDigest),outcome,authority:"candidate"},"candidateDigest");
  return {policy,evidence,technicalCoverage,subject,evaluation,candidate,candidateRawBytes:Buffer.from(canonicalJson(candidate)),subjectContext:{integratedSystemCandidate,systemVerificationResult,technicalCoverage,policy,evidence,repositoryReleaseSnapshot:ref("REL"),traceabilityCheckpoint:ref("TRACE")}};
}
function store(){const values=new Map();return{values,async get(k){return values.get(k)},async put(k,v){if(values.has(k))throw new Error("immutable");values.set(k,structuredClone(v))}}}
function approvalFor(candidate,bytes,technicalCoverage,decision="approved"){return seal({apiVersion:API,kind:"BusinessAcceptanceOwnerApproval",approvalId:`APP-${decision}`,candidate:ref(candidate.candidateId,candidate.candidateDigest),candidateRawDigest:sha256Digest(bytes),decision,owner:{ownerId:"OWNER",authority:"business-owner"},approvedContext:{subject:candidate.subject,policy:candidate.policy,evidence:candidate.evidence,technicalCoverage:ref(technicalCoverage.coverageId,technicalCoverage.coverageDigest)}},"approvalDigest")}
const approvalBytesFor=(candidate,bytes,technicalCoverage,decision="approved")=>Buffer.from(canonicalJson(approvalFor(candidate,bytes,technicalCoverage,decision)));

for(const decision of ["approved","rejected"]) test(`owner ${decision} produces the exact authoritative record`,async()=>{const f=fixture(),checkpoints=store();const result=await executeBusinessAcceptanceGate({...f,checkpoints,invokeOwner:()=>({approvalRawBytes:approvalBytesFor(f.candidate,f.candidateRawBytes,f.technicalCoverage,decision)})});assert.equal(result.record.outcome,decision==="approved"?"accepted":"rejected");assert.equal(result.record.lifecycleDisposition,decision==="approved"?"construction-complete":"incomplete");assert.equal(result.record.authority,"business-acceptance-gate")});

test("checkpoint replay is deterministic and makes zero additional owner calls",async()=>{const f=fixture(),checkpoints=store();let calls=0;const input={...f,checkpoints,invokeOwner:()=>{calls++;return approvalBytesFor(f.candidate,f.candidateRawBytes,f.technicalCoverage)}};const first=await executeBusinessAcceptanceGate(input),second=await executeBusinessAcceptanceGate(input);assert.equal(calls,1);assert.equal(first.gateCalls,1);assert.equal(second.gateCalls,0);assert.equal(second.replayed,true);assert.deepEqual(second.record,first.record)});

test("replay rejects a changed approval raw digest without another owner call",async()=>{const f=fixture(),checkpoints=store();let calls=0,input={...f,checkpoints,invokeOwner:()=>{calls++;return approvalBytesFor(f.candidate,f.candidateRawBytes,f.technicalCoverage)}};await executeBusinessAcceptanceGate(input);const [key,stored]=[...checkpoints.values][0],changed=seal({...stored,approvalRawDigest:D},"checkpointDigest");checkpoints.values.set(key,changed);await assert.rejects(executeBusinessAcceptanceGate(input),e=>e instanceof BusinessAcceptanceGateError&&e.outputs.length===0);assert.equal(calls,1)});

test("replay rejects substituted technical coverage without rerunning owner or technical tests",async()=>{const f=fixture(),checkpoints=store();let ownerCalls=0,technicalTestCalls=0;const input={...f,checkpoints,invokeOwner:()=>{ownerCalls++;return approvalBytesFor(f.candidate,f.candidateRawBytes,f.technicalCoverage)},runTechnicalTests:()=>{technicalTestCalls++}};await executeBusinessAcceptanceGate(input);const [key,stored]=[...checkpoints.values][0],substituted=seal({...stored,technicalCoverage:seal({...stored.technicalCoverage,coverageId:"OTHER-COVERAGE"},"coverageDigest")},"checkpointDigest");checkpoints.values.set(key,substituted);await assert.rejects(executeBusinessAcceptanceGate(input),error=>error instanceof BusinessAcceptanceGateError&&error.outputs.length===0);assert.equal(ownerCalls,1);assert.equal(technicalTestCalls,0)});

test("ineligible candidate outcomes are output-free and never invoke the owner",async()=>{for(const outcome of ["needs-evidence","rejected"]){const f=fixture(outcome);let calls=0;await assert.rejects(executeBusinessAcceptanceGate({...f,checkpoints:store(),invokeOwner:()=>{calls++}}),e=>e instanceof BusinessAcceptanceGateError&&e.outcome===outcome&&e.outputs.length===0);assert.equal(calls,0)}});

test("rejects noncanonical, modified, stale, and substituted candidate bytes",async()=>{const f=fixture(),invokeOwner=()=>approvalBytesFor(f.candidate,f.candidateRawBytes,f.technicalCoverage);const noncanonical=Buffer.from(JSON.stringify(f.candidate,null,2));await assert.rejects(executeBusinessAcceptanceGate({...f,candidateRawBytes:noncanonical,checkpoints:store(),invokeOwner}),/canonical JSON/);const modified=Buffer.from(canonicalJson({...f.candidate,candidateId:"OTHER"}));await assert.rejects(executeBusinessAcceptanceGate({...f,candidateRawBytes:modified,checkpoints:store(),invokeOwner}),/candidateDigest|lineage/);await assert.rejects(executeBusinessAcceptanceGate({...f,evaluation:{...f.evaluation,evaluationId:"STALE"},checkpoints:store(),invokeOwner}),/invalid|stale|substituted/)});

test("noncanonical, malformed, substituted, changed, and parsed approval output is rejected output-free",async()=>{const f=fixture(),approval=approvalFor(f.candidate,f.candidateRawBytes,f.technicalCoverage);const cases=[approval,Buffer.from(JSON.stringify(approval,null,2)),Buffer.from("{"),Buffer.from([0xff]),Buffer.from(canonicalJson(seal({...approval,candidateRawDigest:D},"approvalDigest"))),Buffer.from(canonicalJson(seal({...approval,candidate:ref("OTHER")},"approvalDigest"))),Buffer.from(canonicalJson(seal({...approval,approvedContext:{...approval.approvedContext,technicalCoverage:ref("OTHER")}},"approvalDigest"))),{approvalRawBytes:approvalBytesFor(f.candidate,f.candidateRawBytes,f.technicalCoverage),extra:true}];for(const value of cases)await assert.rejects(executeBusinessAcceptanceGate({...f,checkpoints:store(),invokeOwner:()=>value}),e=>e instanceof BusinessAcceptanceGateError&&e.outputs.length===0)});

test("missing, stale, malformed, and self-certified technical coverage fail before the owner and remain output-free",async()=>{const f=fixture();const variants=[undefined,seal({...f.technicalCoverage,requirementsBaseline:ref("STALE")},"coverageDigest"),seal({...f.technicalCoverage,entries:[]},"coverageDigest"),seal({...f.technicalCoverage,technicalAuthority:"business-acceptance-gate"},"coverageDigest")];for(const technicalCoverage of variants){let ownerCalls=0,technicalTestCalls=0;await assert.rejects(executeBusinessAcceptanceGate({...f,technicalCoverage,checkpoints:store(),invokeOwner:()=>{ownerCalls++},runTechnicalTests:()=>{technicalTestCalls++}}),error=>error instanceof BusinessAcceptanceGateError&&error.outputs.length===0);assert.equal(ownerCalls,0);assert.equal(technicalTestCalls,0)}});

test("baseline or context drift and owner inability are output-free",async()=>{const f=fixture();for(const drift of [{subject:{...f.subject,policy:ref("STALE")}},{evidence:seal({...f.evidence,requirementsBaseline:ref("STALE")},"evidenceDigest")}])await assert.rejects(executeBusinessAcceptanceGate({...f,...drift,checkpoints:store(),invokeOwner:()=>{throw new Error("must not call")}}),e=>e instanceof BusinessAcceptanceGateError&&e.outputs.length===0);await assert.rejects(executeBusinessAcceptanceGate({...f,checkpoints:store(),invokeOwner:()=>{throw new Error("offline")}}),e=>e instanceof BusinessAcceptanceGateError&&e.outcome==="unable-to-proceed"&&e.outputs.length===0)});
