import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { canonicalJsonDigest } from "../src/content-digest.mjs";
import { documentValidators, validationDetail } from "../src/schema-validation.mjs";
import { CHANGE_INTEGRATION_ARTIFACT_KINDS, ChangeIntegrationArtifactValidationError, validateChangeIntegrationArtifact } from "../src/change-integration-artifact-validator.mjs";

test("integrate-change exposes the exact explicit ProjectOverviewBaseline port",()=>{const module=JSON.parse(readFileSync(new URL("../examples/modules/change-integration.module.json",import.meta.url)));const operation=module.operations.find(({id})=>id==="integrate-change");const expected={name:"project-overview-baseline",schema:"https://devrelay.dev/artifacts/project-overview-baseline/v1",mediaTypes:["application/vnd.devrelay.project-overview-baseline+json"],cardinality:"one",required:true};assert.deepEqual(operation.inputs.filter(({name})=>name===expected.name),[expected]);assert.deepEqual(operation.resultContracts.integrated.requiredInputs,["project-overview-baseline","verified-work-item-subject","integration-input-binding"])});

const D=`sha256:${"a".repeat(64)}`, E=`sha256:${"b".repeat(64)}`, C="1".repeat(40), N="2".repeat(40);
const ref=(artifactId,digest=D)=>({artifactId,digest});
const seal=(value,field)=>({...value,[field]:canonicalJsonDigest(Object.fromEntries(Object.entries(value).filter(([key])=>!["apiVersion","kind",field].includes(key))))});
const reject=(value,context)=>assert.throws(()=>validateChangeIntegrationArtifact(value,context),ChangeIntegrationArtifactValidationError);
const obs=(commit,treeDigest)=>({ref:"refs/heads/main",commit,treeDigest});
const adapter={id:"integration.local",version:"1.0.0",configurationDigest:D};
const permissionDemands=[{kind:"filesystem.read",scope:{values:[".git/objects"]}},{kind:"filesystem.write",scope:{values:["refs/heads/main"]}},{kind:"process.spawn",scope:{values:["bounded-integrator"]}}];
const baselines={requirementsBaseline:ref("RB"),projectOverviewBaseline:ref("POB"),architectureBaseline:ref("AB"),contractDisposition:ref("CD"),workBreakdownBaseline:ref("WBB"),workDependencyBaseline:ref("WDB"),specialistAssignmentBaseline:ref("SAB")};
const transition={targetRef:"refs/heads/main",expectedTargetCommit:C,sourceCommit:N,strategy:"cherry-pick"};
const operation={operationId:"OP-1",transition};
const subject=seal({apiVersion:"devrelay.dev/v1alpha1",kind:"VerifiedWorkItemSubject",subjectId:"SUB",workItem:ref("WI-CI-CONTRACTS"),changeSet:ref("CHANGE"),verificationGateApproval:ref("WIV-GATE"),verificationEvidence:[ref("EVIDENCE")]} ,"subjectDigest");
const binding=seal({apiVersion:"devrelay.dev/v1alpha1",kind:"IntegrationInputBinding",bindingId:"BIND",subject:ref("SUB",subject.subjectDigest),baselines,target:{repositorySnapshot:ref("REPO"),ref:"refs/heads/main",expectedCommit:C},integrationPolicy:ref("POLICY"),adapter,permissionDemands,idempotencyKey:"CI-1"},"bindingDigest");
const plan=seal({apiVersion:"devrelay.dev/v1alpha1",kind:"IntegrationPlan",planId:"PLAN",subject:ref("SUB",subject.subjectDigest),binding:ref("BIND",binding.bindingDigest),verifiedChange:ref("CHANGE"),verifiedChangeDigest:D,baselines,preState:obs(C,D),adapter,permissionDemands,transition,integrationPolicy:ref("POLICY"),idempotencyKey:"CI-1"},"planDigest");
const invocation=seal({apiVersion:"devrelay.dev/v1alpha1",kind:"IntegrationAdapterInvocation",invocationId:"INV",plan:ref("PLAN",plan.planDigest),adapter,permissionDemands,operation},"invocationFingerprint");
const raw={apiVersion:"devrelay.dev/v1alpha1",kind:"RawIntegrationEffectResult",invocationId:"INV",invocationFingerprint:invocation.invocationFingerprint,adapter,terminalState:"integrated",effectState:"applied",operation,preState:obs(C,D),postState:obs(N,E),nativeEvidence:[ref("NATIVE")]};

test("all nine owned artifacts compile and validate",()=>{const values=[subject,binding,plan,invocation,raw,seal({apiVersion:"devrelay.dev/v1alpha1",kind:"IntegrationConflictSet",conflictSetId:"CONFLICT",subject:ref("SUB",subject.subjectDigest),plan:ref("PLAN",plan.planDigest),target:obs(C,D),paths:["src/a.mjs"],targetUnchanged:true,evidence:[ref("NATIVE")]},"conflictDigest"),seal({apiVersion:"devrelay.dev/v1alpha1",kind:"IntegratedChangeRecord",recordId:"REC",subject:ref("SUB",subject.subjectDigest),plan:ref("PLAN",plan.planDigest),preState:obs(C,D),postState:obs(N,E),integrationEvidence:[ref("NATIVE")]},"recordDigest"),seal({apiVersion:"devrelay.dev/v1alpha1",kind:"IntegrationCheckpoint",checkpointId:"CP",invocation:ref("INV",invocation.invocationFingerprint),operation,rawResult:ref("RAW"),state:"effect-recorded",recoveryStatus:"not-required"},"checkpointDigest"),seal({apiVersion:"devrelay.dev/v1alpha1",kind:"ChangeIntegrationTraceabilityInput",integratedChange:ref("REC"),subject:ref("SUB",subject.subjectDigest),repositorySnapshot:ref("REPO-POST"),authority:"approved",scope:"change-integration/integrated"},"traceabilityDigest")];assert.deepEqual(values.map((value,index)=>validateChangeIntegrationArtifact(value,index===2?{subject,binding}:index===3?{plan,binding}:index===4?{invocation}:{}).kind),CHANGE_INTEGRATION_ARTIFACT_KINDS)});
test("unknown fields and stale canonical digests fail closed",()=>{reject({...subject,unknown:true});for(const [value,field,context] of [[subject,"subjectDigest"],[binding,"bindingDigest"],[plan,"planDigest",{subject,binding}],[invocation,"invocationFingerprint",{plan,binding}]])reject({...value,[field]:E},context)});
test("plan binds exact verified bytes, pre-state, adapter, permissions, transition, policy, and idempotency",()=>{assert.equal(validateChangeIntegrationArtifact(plan,{subject,binding}),plan);const changes={verifiedChange:ref("OTHER"),verifiedChangeDigest:E,preState:obs(N,D),adapter:{...adapter,version:"2.0.0"},transition:{...transition,expectedTargetCommit:N},integrationPolicy:ref("OTHER"),idempotencyKey:"OTHER"};for(const [field,value] of Object.entries(changes))reject(seal({...plan,[field]:value},"planDigest"),{subject,binding});reject({...plan,permissionDemands:[{kind:"network.connect",scope:{values:["host:443"]}}]},{subject,binding})});
test("permission demands use only the shared bounded five-kind vocabulary",()=>{for(const kind of ["filesystem.read","filesystem.write","network.connect","process.spawn","secrets.read"]){const demands=[{kind,scope:{values:["bounded"]}}];const validBinding=seal({...binding,permissionDemands:demands},"bindingDigest");const validPlan=seal({...plan,binding:ref("BIND",validBinding.bindingDigest),permissionDemands:demands},"planDigest");assert.equal(validateChangeIntegrationArtifact(validPlan,{subject,binding:validBinding}),validPlan)}for(const kind of ["repository.read","repository.compare-and-swap","graph.write"]){const demands=[{kind,scope:{values:["bounded"]}}];reject(seal({...binding,permissionDemands:demands},"bindingDigest"))}reject(seal({...binding,permissionDemands:[{kind:"filesystem.write",scope:{values:[]}}]},"bindingDigest"))});
test("binding owns every project baseline and plan equality rejects omission, addition, reordering, and substitution",()=>{assert.equal(validateChangeIntegrationArtifact(binding),binding);const omitted=structuredClone(binding);delete omitted.baselines.architectureBaseline;reject(seal(omitted,"bindingDigest"));reject(seal({...binding,baselines:{...baselines,otherBaseline:ref("OTHER")}},"bindingDigest"));const substituted=seal({...plan,baselines:{...baselines,workDependencyBaseline:ref("OTHER")}},"planDigest");reject(substituted,{subject,binding});const reordered=seal({...plan,permissionDemands:[...permissionDemands].reverse()},"planDigest");reject(reordered,{subject,binding});const omittedDemand=seal({...plan,permissionDemands:permissionDemands.slice(0,-1)},"planDigest");reject(omittedDemand,{subject,binding});const addedDemand=seal({...plan,permissionDemands:[...permissionDemands,{kind:"network.connect",scope:{values:["host:443"]}}]},"planDigest");reject(addedDemand,{subject,binding})});
test("adapter substitution, changed operation, and downstream authority fail closed",()=>{reject({...raw,adapter:{...adapter,id:"integration.other"}},{invocation});reject({...raw,operation:{...operation,operationId:"OTHER"}},{invocation});for(const field of ["verified","systemVerified","businessAccepted","graphMutation","approval"])reject({...raw,[field]:true},{invocation})});
test("interrupted and uncertain raw effects preserve unresolved operation state",()=>{for(const value of [{...raw,terminalState:"interrupted",effectState:"unknown",postState:undefined},{...raw,terminalState:"uncertain",effectState:"unknown",postState:obs(N,E)},{...raw,terminalState:"failed",effectState:"applied"}]){const candidate=Object.fromEntries(Object.entries(value).filter(([,entry])=>entry!==undefined));assert.equal(validateChangeIntegrationArtifact(candidate,{invocation}),candidate)}reject({...raw,terminalState:"integrated",effectState:"unknown"},{invocation})});
test("checkpoint represents prepared, recorded, and reconciled recovery states",()=>{const prepared=seal({apiVersion:"devrelay.dev/v1alpha1",kind:"IntegrationCheckpoint",checkpointId:"CP-P",invocation:ref("INV",invocation.invocationFingerprint),operation,state:"prepared",recoveryStatus:"pending"},"checkpointDigest");const recorded=seal({...prepared,checkpointId:"CP-E",rawResult:ref("RAW"),state:"effect-recorded",recoveryStatus:"needs-reconciliation"},"checkpointDigest");const reconciled=seal({...recorded,checkpointId:"CP-R",state:"reconciled",recoveryStatus:"recovered",observedState:obs(N,E)},"checkpointDigest");for(const value of [prepared,recorded,reconciled])assert.equal(validateChangeIntegrationArtifact(value),value);reject(seal({...prepared,rawResult:ref("RAW")},"checkpointDigest"));const missingObserved={...reconciled};delete missingObserved.observedState;reject(seal(missingObserved,"checkpointDigest"))});
test("reconciled recoveryEvidence is a closed alternative that never fabricates a raw result",()=>{const recoveryCheckpoint=(recoveryEvidence,recoveryStatus="recovered",nextOperation=operation)=>seal({apiVersion:"devrelay.dev/v1alpha1",kind:"IntegrationCheckpoint",checkpointId:"CP-RECOVERY",invocation:ref("INV",invocation.invocationFingerprint),operation:nextOperation,recoveryEvidence,state:"reconciled",recoveryStatus},"checkpointDigest");const notApplied=recoveryCheckpoint({disposition:"not-applied",observedState:obs(C,E),observationEvidence:ref("OBSERVATION")});const fastForwardOperation={...operation,transition:{...transition,strategy:"fast-forward"}};const fastForward=recoveryCheckpoint({disposition:"applied",observedState:obs(N,E),observationEvidence:ref("OBSERVATION")},"recovered",fastForwardOperation);const authorizedMerge=recoveryCheckpoint({disposition:"applied",observedState:obs("3".repeat(40),E),observationEvidence:ref("OBSERVATION"),producedCommitAuthorization:ref("PRODUCED-COMMIT-AUTH")});const unresolved=recoveryCheckpoint({disposition:"unresolved",observedState:obs("4".repeat(40),E),observationEvidence:ref("OBSERVATION")},"needs-reconciliation");for(const value of [notApplied,fastForward,authorizedMerge,unresolved]){assert.equal(validateChangeIntegrationArtifact(value),value);assert.equal("rawResult" in value,false)}assert.equal(CHANGE_INTEGRATION_ARTIFACT_KINDS.includes("RawIntegrationEffectResult"),true)});
test("recovery reconciliation proof paths are mutually exclusive and evidence-complete",()=>{const evidence={disposition:"not-applied",observedState:obs(C,E),observationEvidence:ref("OBSERVATION")};const base={apiVersion:"devrelay.dev/v1alpha1",kind:"IntegrationCheckpoint",checkpointId:"CP-X",invocation:ref("INV",invocation.invocationFingerprint),operation,state:"reconciled",recoveryStatus:"recovered"};reject(seal(base,"checkpointDigest"));reject(seal({...base,recoveryEvidence:evidence,rawResult:ref("RAW"),observedState:obs(C,E)},"checkpointDigest"));const missing={...evidence};delete missing.observationEvidence;reject(seal({...base,recoveryEvidence:missing},"checkpointDigest"));reject(seal({...base,recoveryEvidence:{...evidence,unknown:true}},"checkpointDigest"));reject(seal({...base,recoveryEvidence:{...evidence,observedState:{...evidence.observedState,ref:"refs/heads/other"}}},"checkpointDigest"));reject(seal({...base,recoveryEvidence:{...evidence,observedState:obs(N,E)}},"checkpointDigest"))});
test("applied recovery evidence is strategy-aware and authorizes every produced commit",()=>{const base={apiVersion:"devrelay.dev/v1alpha1",kind:"IntegrationCheckpoint",checkpointId:"CP-A",invocation:ref("INV",invocation.invocationFingerprint),state:"reconciled",recoveryStatus:"recovered"};const recoveryEvidence={disposition:"applied",observedState:obs(N,E),observationEvidence:ref("OBSERVATION")};for(const strategy of ["merge-commit","cherry-pick"]){const nextOperation={...operation,transition:{...transition,strategy}};reject(seal({...base,operation:nextOperation,recoveryEvidence},"checkpointDigest"));assert.equal(validateChangeIntegrationArtifact(seal({...base,operation:nextOperation,recoveryEvidence:{...recoveryEvidence,producedCommitAuthorization:ref("AUTH")}},"checkpointDigest")).kind,"IntegrationCheckpoint")}const fastForward={...operation,transition:{...transition,strategy:"fast-forward"}};reject(seal({...base,operation:fastForward,recoveryEvidence:{...recoveryEvidence,observedState:obs("3".repeat(40),E)}},"checkpointDigest"));assert.equal(validateChangeIntegrationArtifact(seal({...base,operation:fastForward,recoveryEvidence:{...recoveryEvidence,observedState:obs("3".repeat(40),E),producedCommitAuthorization:ref("AUTH")}},"checkpointDigest")).kind,"IntegrationCheckpoint");reject(seal({...base,operation:fastForward,recoveryStatus:"needs-reconciliation",recoveryEvidence},"checkpointDigest"));reject(seal({...base,operation:fastForward,recoveryStatus:"recovered",recoveryEvidence:{...recoveryEvidence,disposition:"unresolved"}},"checkpointDigest"))});
test("module reuses the RepositorySnapshot owner and retains attempt-002 boundaries",()=>{const module=JSON.parse(readFileSync(new URL("../examples/modules/change-integration.module.json",import.meta.url)));assert.equal(documentValidators.moduleDefinition(module),true,validationDetail(documentValidators.moduleDefinition));const operationDef=module.operations[0];assert.match(operationDef.description,/checkpoint recovery.*raw-result observation or closed recovery evidence/);assert.deepEqual(operationDef.outcomes,["integrated","integration-conflict","baseline-drift","unable-to-proceed","execution-failed"]);assert.deepEqual(operationDef.evidence,["change-integration/native-effect","change-integration/post-state"]);assert.equal(JSON.stringify(operationDef).includes("change-integration/contract-tests"),false);assert.ok(operationDef.orchestrationPlan.findIndex(({id})=>id==="checkpoint-recovery")<operationDef.orchestrationPlan.findIndex(({id})=>id==="result-validation"));assert.deepEqual(operationDef.outputs.find(({name})=>name==="repository-snapshot"),{name:"repository-snapshot",schema:"https://devrelay.dev/artifacts/repository-snapshot/v1",mediaTypes:["application/vnd.devrelay.repository-snapshot+json"],cardinality:"one",required:false});assert.equal(JSON.stringify(operationDef).includes("PostIntegrationRepositorySnapshot"),false);assert.deepEqual(operationDef.extensionPorts,[{id:"integration-adapter",role:"proposer",inputSchema:"https://devrelay.dev/contracts/change-integration-artifacts.schema.json#/$defs/adapterInvocation",outputSchema:"https://devrelay.dev/contracts/change-integration-artifacts.schema.json#/$defs/rawEffectResult",required:true}]);const port=JSON.stringify(operationDef.extensionPorts).toLowerCase();for(const forbidden of ["git","github","systemverification","businessacceptance","traceability","approval"])assert.equal(port.includes(forbidden),false,forbidden)});
