import assert from "node:assert/strict";
import test from "node:test";
import { canonicalJson, canonicalJsonDigest } from "../src/content-digest.mjs";
import { ChangeIntegrationCheckpointError, createChangeIntegrationCheckpointController } from "../src/change-integration-checkpoint.mjs";

const D=`sha256:${"a".repeat(64)}`, E=`sha256:${"b".repeat(64)}`, C="1".repeat(40), N="2".repeat(40), X="3".repeat(40);
const ref=(artifactId,digest=D)=>({artifactId,digest});
const seal=(value,field)=>({...value,[field]:canonicalJsonDigest(Object.fromEntries(Object.entries(value).filter(([key])=>!["apiVersion","kind",field].includes(key))))});
const adapter={id:"integration.local",version:"1.0.0",configurationDigest:D};
const permissionDemands=[{kind:"process.spawn",scope:{values:["bounded-integrator"]}}];
const baselines={requirementsBaseline:ref("RB"),projectOverviewBaseline:ref("POB"),architectureBaseline:ref("AB"),contractDisposition:ref("CD"),workBreakdownBaseline:ref("WBB"),workDependencyBaseline:ref("WDB"),specialistAssignmentBaseline:ref("SAB")};
const transition={targetRef:"refs/heads/main",expectedTargetCommit:C,sourceCommit:N,strategy:"cherry-pick"};
const plan=seal({apiVersion:"devrelay.dev/v1alpha1",kind:"IntegrationPlan",planId:"PLAN",subject:ref("SUB"),binding:ref("BIND"),verifiedChange:ref("CHANGE"),verifiedChangeDigest:D,baselines,preState:{ref:"refs/heads/main",commit:C,treeDigest:D},adapter,permissionDemands,transition,integrationPolicy:ref("POLICY"),idempotencyKey:"CI-1"},"planDigest");
const operation={operationId:"INV",transition};
const invocation=seal({apiVersion:"devrelay.dev/v1alpha1",kind:"IntegrationAdapterInvocation",invocationId:"INV",plan:ref("PLAN",plan.planDigest),adapter,permissionDemands,operation},"invocationFingerprint");
const observation=(commit,treeDigest=E)=>({ref:"refs/heads/main",commit,treeDigest});
const observationEvidence=ref("OBSERVATION-EVIDENCE",E);
const raw=(terminalState="integrated",effectState="applied",post=N)=>({apiVersion:"devrelay.dev/v1alpha1",kind:"RawIntegrationEffectResult",invocationId:"INV",invocationFingerprint:invocation.invocationFingerprint,adapter,terminalState,effectState,operation,preState:observation(C,D),...(post?{postState:observation(post)}:{}),nativeEvidence:[ref("NATIVE")]});
const variant=(strategy,id)=>{const nextTransition={...transition,strategy};const nextPlan=seal({...plan,planId:`PLAN-${id}`,idempotencyKey:`CI-${id}`,transition:nextTransition},"planDigest");const nextOperation={operationId:`INV-${id}`,transition:nextTransition};const nextInvocation=seal({...invocation,invocationId:`INV-${id}`,plan:ref(nextPlan.planId,nextPlan.planDigest),operation:nextOperation},"invocationFingerprint");return {plan:nextPlan,invocation:nextInvocation}};
function store(){const values=new Map();return {values,async get(key){return values.get(key)},async put(key,value){if(values.has(key))throw new Error("overwrite");values.set(key,structuredClone(value))}}}
function rawStore(){const values=new Map();return {values,async persist(bytes){const digest=`sha256:${(await import("node:crypto")).createHash("sha256").update(bytes).digest("hex")}`;const value={artifactId:`RAW-${values.size}`,digest};values.set(digest,Buffer.from(bytes));return value},async read(reference){return values.get(reference.digest)}}}
function fixture(effect){const checkpoints=store(),results=rawStore();return {checkpoints,results,controller:createChangeIntegrationCheckpointController({effect,persistRawResult:results.persist,readRawResult:results.read})}}

test("prepared is durable before the effect and exact replay makes zero duplicate calls",async()=>{let calls=0;const f=fixture(async()=>{calls++;assert.equal(f.checkpoints.values.size,1);return raw()});const first=await f.controller.execute({plan,invocation,checkpoints:f.checkpoints});const replay=await f.controller.execute({plan,invocation,checkpoints:f.checkpoints});assert.equal(calls,1);assert.equal(first.checkpoint.state,"effect-recorded");assert.equal(replay.replayed,true);assert.equal(replay.effectCalls,0);assert.deepEqual(Buffer.from(replay.nativeBytes),Buffer.from(canonicalJson(raw())))});
test("failure, conflict, and interruption results are persisted and replayed exactly",async()=>{for(const result of [raw("failed","not-applied",null),raw("conflict","not-applied",null),raw("interrupted","unknown",null)]){if(result.terminalState==="conflict")result.conflictingPaths=["src/a.mjs"];let calls=0;const f=fixture(async()=>{calls++;return result});await f.controller.execute({plan,invocation,checkpoints:f.checkpoints});const replay=await f.controller.execute({plan,invocation,checkpoints:f.checkpoints});assert.equal(calls,1);assert.deepEqual(replay.rawResult,result)}});
test("a crash after prepared never blindly invokes the adapter",async()=>{let calls=0;const f=fixture(async()=>{calls++;throw new Error("crash")});const first=await f.controller.execute({plan,invocation,checkpoints:f.checkpoints});const replay=await f.controller.execute({plan,invocation,checkpoints:f.checkpoints});assert.equal(first.recoveryStatus,"pending");assert.equal(replay.recoveryStatus,"pending");assert.equal(calls,1)});
test("a real prepared-only crash durably recovers fast-forward and survives controller restart",async()=>{const subject=variant("fast-forward","FF-CRASH");let target=C,calls=0;const effect=async()=>{calls++;target=N;throw new Error("crash after mutation")};const f=fixture(effect);await f.controller.execute({...subject,checkpoints:f.checkpoints});const recovered=await f.controller.execute({...subject,checkpoints:f.checkpoints,observation:observation(target),observationEvidence});assert.equal(recovered.checkpoint.state,"reconciled");assert.equal(recovered.recoveryEvidence.disposition,"applied");assert.equal("rawResult" in recovered.checkpoint,false);const restarted=createChangeIntegrationCheckpointController({effect,persistRawResult:f.results.persist,readRawResult:f.results.read});const replay=await restarted.execute({...subject,checkpoints:f.checkpoints});assert.equal(replay.checkpointDigest,recovered.checkpointDigest);assert.equal(replay.effectCalls,0);assert.equal(calls,1)});
test("prepared-only unresolved merge and cherry-pick checkpoints survive restart",async()=>{for(const strategy of ["merge-commit","cherry-pick"]){const subject=variant(strategy,`CRASH-${strategy}`);let target=C,calls=0;const effect=async()=>{calls++;target=N;throw new Error("crash after mutation")};const f=fixture(effect);await f.controller.execute({...subject,checkpoints:f.checkpoints});const unresolved=await f.controller.execute({...subject,checkpoints:f.checkpoints,observation:observation(target),observationEvidence});assert.equal(unresolved.recoveryStatus,"needs-reconciliation");assert.equal(unresolved.recoveryEvidence.disposition,"unresolved");const restarted=createChangeIntegrationCheckpointController({effect,persistRawResult:f.results.persist,readRawResult:f.results.read});const replay=await restarted.execute({...subject,checkpoints:f.checkpoints});assert.equal(replay.checkpointDigest,unresolved.checkpointDigest);assert.equal(replay.effectCalls,0);assert.equal(calls,1)}});
test("trusted observations reconcile uncertain effects without another mutation",async()=>{for(const [commit,status] of [[C,"recovered"],[N,"recovered"],[X,"needs-reconciliation"]]){let calls=0;const f=fixture(async()=>{calls++;return raw("uncertain","unknown",N)});await f.controller.execute({plan,invocation,checkpoints:f.checkpoints});const recovered=await f.controller.reconcile({plan,invocation,checkpoints:f.checkpoints,observation:observation(commit),observationEvidence});const replay=await f.controller.execute({plan,invocation,checkpoints:f.checkpoints});assert.equal(recovered.recoveryStatus,status);assert.deepEqual(recovered.observationEvidence,observationEvidence);assert.equal(replay.effectCalls,0);assert.equal(calls,1)}});
test("uncertain cherry-pick sourceCommit is not proof, but exact persisted postState is",async()=>{let calls=0;const withoutPost=fixture(async()=>{calls++;return raw("uncertain","unknown",null)});await withoutPost.controller.execute({plan,invocation,checkpoints:withoutPost.checkpoints});const unresolved=await withoutPost.controller.reconcile({plan,invocation,checkpoints:withoutPost.checkpoints,observation:observation(N),observationEvidence});assert.equal(unresolved.recoveryStatus,"needs-reconciliation");const withPost=fixture(async()=>raw("uncertain","unknown",X));await withPost.controller.execute({plan,invocation,checkpoints:withPost.checkpoints});const recovered=await withPost.controller.reconcile({plan,invocation,checkpoints:withPost.checkpoints,observation:observation(X),observationEvidence});assert.equal(recovered.recoveryStatus,"recovered");assert.equal(calls,1)});
test("separate trusted produced-commit evidence stores only its exact ref",async()=>{const subject=variant("merge-commit","AUTH");let calls=0;const f=fixture(async()=>{calls++;throw new Error("crash after mutation")});await f.controller.execute({...subject,checkpoints:f.checkpoints});const authorizationRef=ref("PRODUCED-AUTHORIZATION");const authorization={invocationId:subject.invocation.invocationId,invocationFingerprint:subject.invocation.invocationFingerprint,targetRef:"refs/heads/main",commit:X,artifact:authorizationRef};const recovered=await f.controller.execute({...subject,checkpoints:f.checkpoints,observation:observation(X),observationEvidence,producedCommitAuthorization:authorization});assert.equal(recovered.recoveryEvidence.disposition,"applied");assert.deepEqual(recovered.recoveryEvidence.producedCommitAuthorization,authorizationRef);assert.equal(JSON.stringify(recovered.checkpoint).includes(subject.invocation.invocationFingerprint),true);assert.equal("rawResult" in recovered.checkpoint,false);assert.equal(calls,1)});
test("reconciliation rejects an observation without exact persisted evidence",async()=>{const subject=variant("fast-forward","NO-EVIDENCE");const f=fixture(async()=>{throw new Error("crash")});await f.controller.execute({...subject,checkpoints:f.checkpoints});await assert.rejects(f.controller.execute({...subject,checkpoints:f.checkpoints,observation:observation(N)}),e=>e.code==="DR4101");const recorded=fixture(async()=>raw("uncertain","unknown",null));await recorded.controller.execute({plan,invocation,checkpoints:recorded.checkpoints});await assert.rejects(recorded.controller.reconcile({plan,invocation,checkpoints:recorded.checkpoints,observation:observation(N)}),e=>e.code==="DR4101")});
test("same idempotency identity with changed plan or invocation fails closed",async()=>{let calls=0;const f=fixture(async()=>{calls++;return raw()});await f.controller.execute({plan,invocation,checkpoints:f.checkpoints});const changedPlan=seal({...plan,transition:{...transition,strategy:"fast-forward"}},"planDigest");const changedInvocation=seal({...invocation,plan:ref("PLAN",changedPlan.planDigest),operation:{...operation,transition:changedPlan.transition}},"invocationFingerprint");await assert.rejects(f.controller.execute({plan:changedPlan,invocation:changedInvocation,checkpoints:f.checkpoints}),ChangeIntegrationCheckpointError);assert.equal(calls,1)});
test("immutable persistence and exact raw bytes are enforced",async()=>{const f=fixture(async()=>raw());await f.controller.execute({plan,invocation,checkpoints:f.checkpoints});const rawEntry=[...f.results.values.keys()][0];f.results.values.set(rawEntry,Buffer.from("{}"));await assert.rejects(f.controller.execute({plan,invocation,checkpoints:f.checkpoints}),e=>e.code==="DR4098");await assert.rejects(f.controller.reconcile({plan,invocation,checkpoints:f.checkpoints,observation:observation(N),observationEvidence}),e=>e.code==="DR4098")});
