import assert from "node:assert/strict";
import test from "node:test";
import { canonicalJsonDigest } from "../src/content-digest.mjs";
import { assembleSystemVerificationResult, evaluateSystemVerificationPolicy, executeSystemVerification, expandSystemVerificationObligations, validateIntegratedSystemCandidate } from "../src/system-verification-core.mjs";

const base={apiVersion:"devrelay.dev/v1alpha1"};
const ref=(artifactId,digest="sha256:"+"1".repeat(64))=>({artifactId,digest});
const seal=(body,field)=>({...body,[field]:canonicalJsonDigest(Object.fromEntries(Object.entries(body).filter(([key])=>!["apiVersion","kind",field].includes(key))))});
const subject=seal({...base,kind:"IntegratedSystemCandidate",subjectId:"SYSTEM-1",repositorySnapshot:ref("REPO"),integratedChangeRecords:[ref("CHANGE")],integratedCompletionFactSet:ref("FACTS"),requirementsBaseline:ref("REQ"),projectOverviewBaseline:ref("OVERVIEW"),architectureBaseline:ref("ARCH"),contractDisposition:ref("CONTRACT"),workBreakdownBaseline:ref("WORK"),workDependencyBaseline:ref("DAG"),specialistAssignmentBaseline:ref("ASSIGN"),verificationEnvironment:ref("ENV"),systemVerificationPolicy:ref("POLICY")} ,"subjectDigest");
const policy=seal({...base,kind:"SystemVerificationPolicy",policyId:"POLICY",version:"1.0.0",allObligationsMandatory:true,unknownEvidence:"reject",outcomePrecedence:["failed","needs-evidence","verified"]},"policyDigest");
const criteria=[{id:"AC-2",requiredEvidenceKinds:["test"]},{id:"AC-1",requiredEvidenceKinds:["test"]}];
const nfrs=[{id:"NFR-1",requiredEvidenceKinds:["review"]}];
const invocationFor=(obligations)=>seal({...base,kind:"SystemVerifierInvocation",invocationId:"INVOKE-1",subject:ref(subject.subjectId,subject.subjectDigest),obligationSet:ref(obligations.obligationSetId,obligations.obligationSetDigest),policy:ref(policy.policyId,policy.policyDigest),verifier:{id:"fixture-verifier",version:"1.0.0"},assignedObligationIds:obligations.obligations.map(x=>x.obligationId),verificationEnvironment:subject.verificationEnvironment,grants:[]},"invocationFingerprint");
const rawFor=(invocation,obligations,status="pass")=>{const observations=obligations.obligations.map((x,index)=>({obligationId:x.obligationId,status,evidenceBindings:[{kind:x.requiredEvidenceKinds[0],artifact:ref(`ASSERTION-EVIDENCE-${index}`)}]}));return seal({...base,kind:"RawSystemVerifierObservation",observationId:"RAW-1",invocationFingerprint:invocation.invocationFingerprint,subject:invocation.subject,obligationSet:invocation.obligationSet,verifier:invocation.verifier,observations,nativeEvidence:[ref("ADAPTER-NATIVE-RESULT")]},"rawObservationDigest")};
const store=()=>{const values=new Map();return{values,get:key=>values.get(key),put:(key,value)=>{if(values.has(key))throw new Error("immutable");values.set(key,structuredClone(value))}}};

test("Core expands acceptance criteria and applicable NFRs deterministically",()=>{const a=expandSystemVerificationObligations({subject,acceptanceCriteria:criteria,nonFunctionalRequirements:nfrs});const b=expandSystemVerificationObligations({subject,acceptanceCriteria:[...criteria].reverse(),nonFunctionalRequirements:nfrs});assert.deepEqual(a,b);assert.deepEqual(a.obligations.map(x=>x.sourceRef),["AC-1","AC-2","NFR-1"])});

test("exact replay calls the untrusted verifier zero additional times and assembles verified progression",async()=>{const obligations=expandSystemVerificationObligations({subject,acceptanceCriteria:criteria,nonFunctionalRequirements:nfrs}),invocation=invocationFor(obligations),checkpoints=store();let calls=0;const input={subject,policy,acceptanceCriteria:criteria,nonFunctionalRequirements:nfrs,invocations:[invocation],checkpoints,verifier:async value=>{calls++;assert.equal(value.invocationId,"INVOKE-1");return rawFor(value,obligations)}};const first=await executeSystemVerification(input),second=await executeSystemVerification(input);assert.equal(calls,1);assert.equal(first.result.outcome,"verified");assert.equal(first.result.progression,"business-acceptance-gate");assert.equal(second.checkpointReplays[0].verifierCalls,0);assert.deepEqual(first.result,second.result)});

test("native-result provenance remains distinct from extracted assertion evidence",async()=>{const obligations=expandSystemVerificationObligations({subject,acceptanceCriteria:criteria,nonFunctionalRequirements:nfrs}),invocation=invocationFor(obligations),checkpoints=store(),raw=rawFor(invocation,obligations);const result=await executeSystemVerification({subject,policy,acceptanceCriteria:criteria,nonFunctionalRequirements:nfrs,invocations:[invocation],checkpoints,verifier:async()=>raw});assert.deepEqual(raw.nativeEvidence,[ref("ADAPTER-NATIVE-RESULT")]);assert.ok(result.evidence.items.every(item=>item.artifact.artifactId.startsWith("ASSERTION-EVIDENCE-")));assert.ok(result.evidence.items.every(item=>item.artifact.artifactId!==raw.nativeEvidence[0].artifactId))});

test("typed assertion evidence rejects unknown kinds and duplicate bindings",async()=>{for(const variant of ["unknown","duplicate"]){const obligations=expandSystemVerificationObligations({subject,acceptanceCriteria:criteria,nonFunctionalRequirements:nfrs}),invocation=invocationFor(obligations),raw=rawFor(invocation,obligations),binding=raw.observations[0].evidenceBindings[0];raw.observations[0].evidenceBindings=variant==="unknown"?[{...binding,kind:"adapter-invented-kind"}]:[binding,structuredClone(binding)];delete raw.rawObservationDigest;raw.rawObservationDigest=seal(raw,"rawObservationDigest").rawObservationDigest;await assert.rejects(executeSystemVerification({subject,policy,acceptanceCriteria:criteria,nonFunctionalRequirements:nfrs,invocations:[invocation],checkpoints:store(),verifier:async()=>raw}),variant==="unknown"?/unknown evidence kind/:/duplicate evidence binding/)}});

test("policy precedence produces failed and needs-evidence without progression",()=>{const obligations=expandSystemVerificationObligations({subject,acceptanceCriteria:criteria.slice(0,1),nonFunctionalRequirements:[]});for(const [items,outcome] of [[[],"needs-evidence"],[[{evidenceId:"E",obligationId:obligations.obligations[0].obligationId,kind:"test",status:"fail",artifact:ref("E"),producer:{id:"v",version:"1.0.0"}}],"failed"]]){const evidence=seal({...base,kind:"NormalizedSystemVerificationEvidence",evidenceSetId:`SET-${outcome}`,subject:ref(subject.subjectId,subject.subjectDigest),obligationSet:ref(obligations.obligationSetId,obligations.obligationSetDigest),rawObservations:[ref("RAW")],items:items.flat()},"evidenceDigest");const evaluation=evaluateSystemVerificationPolicy({subject,obligations,policy,evidence}),result=assembleSystemVerificationResult({subject,obligations,policy,evidence,evaluation});assert.equal(result.outcome,outcome);assert.equal(result.progression,"none")}});

test("fully resealed substituted evidence lineage fails before policy evaluation",()=>{const obligations=expandSystemVerificationObligations({subject,acceptanceCriteria:criteria.slice(0,1),nonFunctionalRequirements:[]});const evidence=seal({...base,kind:"NormalizedSystemVerificationEvidence",evidenceSetId:"SET-SUBSTITUTED",subject:ref("OTHER-SYSTEM"),obligationSet:ref(obligations.obligationSetId,obligations.obligationSetDigest),rawObservations:[ref("RAW")],items:[]},"evidenceDigest");assert.throws(()=>evaluateSystemVerificationPolicy({subject,obligations,policy,evidence}),/stale or substituted artifact reference/)});

test("subject baseline substitution fails closed as baseline-drift",()=>{assert.throws(()=>validateIntegratedSystemCandidate(subject,{repositorySnapshot:ref("OTHER")}),error=>error.outcome==="baseline-drift")});

test("malformed subjects fail closed as unable-to-proceed",()=>{assert.throws(()=>validateIntegratedSystemCandidate({...subject,authority:"adapter"}),error=>error.outcome==="unable-to-proceed")});
