import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { canonicalJsonDigest } from "../src/content-digest.mjs";
import { documentValidators } from "../src/schema-validation.mjs";
import { validateSystemVerificationArtifact } from "../src/system-verification-artifact-validator.mjs";

const D="sha256:"+"a".repeat(64), ref=(artifactId,digest=D)=>({artifactId,digest});
const seal=(value,field)=>({...value,[field]:canonicalJsonDigest(Object.fromEntries(Object.entries(value).filter(([k])=>!["apiVersion","kind",field].includes(k))))});
const base={apiVersion:"devrelay.dev/v1alpha1"};
const subject=seal({...base,kind:"IntegratedSystemCandidate",subjectId:"SYS-1",repositorySnapshot:ref("REPO"),integratedChangeRecords:[ref("ICR-1")],integratedCompletionFactSet:ref("INTEGRATED-COMPLETION-FACT-SET"),requirementsBaseline:ref("REQ"),projectOverviewBaseline:ref("PO"),architectureBaseline:ref("ARCH"),contractDisposition:ref("CONTRACT"),workBreakdownBaseline:ref("WB"),workDependencyBaseline:ref("WD"),specialistAssignmentBaseline:ref("SA"),verificationEnvironment:{disposition:"approved-not-applicable",rationale:"Hermetic verification"},systemVerificationPolicy:ref("POL")},"subjectDigest");
const obligations=seal({...base,kind:"SystemVerificationObligationSet",obligationSetId:"OBS",subject:ref(subject.subjectId,subject.subjectDigest),obligations:[{obligationId:"OB-AC",kind:"acceptance-criterion",sourceRef:"AC-1",requiredEvidenceKinds:["test"]},{obligationId:"OB-NFR",kind:"non-functional-requirement",sourceRef:"NFR-1",requiredEvidenceKinds:["review"]}]},"obligationSetDigest");
const policy=seal({...base,kind:"SystemVerificationPolicy",policyId:"POL",version:"1.0.0",allObligationsMandatory:true,unknownEvidence:"reject",outcomePrecedence:["failed","needs-evidence","verified"]},"policyDigest");
const invocation=seal({...base,kind:"SystemVerifierInvocation",invocationId:"INV-1",subject:ref(subject.subjectId,subject.subjectDigest),obligationSet:ref(obligations.obligationSetId,obligations.obligationSetDigest),policy:ref(policy.policyId,policy.policyDigest),verifier:{id:"system-test-verifier",version:"1.0.0"},assignedObligationIds:["OB-AC","OB-NFR"],verificationEnvironment:subject.verificationEnvironment,grants:[{kind:"filesystem.read",scope:{values:["workspace"]}},{kind:"process.spawn",scope:{values:["node"]}}]},"invocationFingerprint");
const rawObservation=seal({...base,kind:"RawSystemVerifierObservation",observationId:"RAW",invocationFingerprint:invocation.invocationFingerprint,subject:invocation.subject,obligationSet:invocation.obligationSet,verifier:invocation.verifier,observations:[{obligationId:"OB-AC",status:"pass",evidenceBindings:[{kind:"test",artifact:ref("TEST-EVIDENCE")}]},{obligationId:"OB-NFR",status:"inconclusive",evidenceBindings:[]}],nativeEvidence:[ref("NATIVE-LOG")]},"rawObservationDigest");
const evidence=seal({...base,kind:"NormalizedSystemVerificationEvidence",evidenceSetId:"EV",subject:ref(subject.subjectId,subject.subjectDigest),obligationSet:ref(obligations.obligationSetId,obligations.obligationSetDigest),rawObservations:[ref("RAW")],items:[]},"evidenceDigest");
const evaluation=seal({...base,kind:"SystemVerificationEvaluation",evaluationId:"EVAL",subject:ref(subject.subjectId,subject.subjectDigest),obligationSet:ref(obligations.obligationSetId,obligations.obligationSetDigest),policy:ref(policy.policyId,policy.policyDigest),evidence:ref(evidence.evidenceSetId,evidence.evidenceDigest),dispositions:[{obligationId:"OB-AC",status:"satisfied",evidenceIds:["EV-1"]},{obligationId:"OB-NFR",status:"satisfied",evidenceIds:["EV-2"]}],outcome:"verified"},"evaluationDigest");
const result=seal({...base,kind:"SystemVerificationResult",resultId:"RESULT",subject:ref(subject.subjectId,subject.subjectDigest),obligationSet:ref(obligations.obligationSetId,obligations.obligationSetDigest),policy:ref(policy.policyId,policy.policyDigest),evidence:ref(evidence.evidenceSetId,evidence.evidenceDigest),evaluation:ref(evaluation.evaluationId,evaluation.evaluationDigest),outcome:"verified",progression:"business-acceptance-gate",authority:"system-verification"},"resultDigest");
const reject=(value,context={})=>assert.throws(()=>validateSystemVerificationArtifact(value,context),/system verification artifact is invalid/);

test("closed canonical artifact family accepts valid digest-bound artifacts",()=>{for(const value of [subject,obligations,policy]) assert.equal(validateSystemVerificationArtifact(value),value);assert.equal(validateSystemVerificationArtifact(invocation,{subject,obligations,policy}),invocation);assert.equal(validateSystemVerificationArtifact(rawObservation,{invocation}),rawObservation);assert.equal(validateSystemVerificationArtifact(evidence,{subject,obligations}),evidence);assert.equal(validateSystemVerificationArtifact(evaluation,{subject,obligations,policy,evidence}),evaluation);assert.equal(validateSystemVerificationArtifact(result,{evaluation}),result)});
test("accepts a valid zero-change integrated system subject",()=>{const zeroChange=seal({...subject,subjectId:"SYS-NO-WORK",integratedChangeRecords:[],integratedCompletionFactSet:ref("EMPTY-INTEGRATED-COMPLETION-FACT-SET")},"subjectDigest");assert.equal(validateSystemVerificationArtifact(zeroChange),zeroChange)});
test("invocation and raw observation reject substitution and unknown fields",()=>{reject({...invocation,ambientPolicy:"forbidden"},{subject,obligations,policy});reject(seal({...invocation,policy:ref("OTHER-POLICY",policy.policyDigest)},"invocationFingerprint"),{subject,obligations,policy});reject(seal({...invocation,verificationEnvironment:{disposition:"approved-not-applicable",rationale:"substituted"}},"invocationFingerprint"),{subject,obligations,policy});reject({...rawObservation,adapterDecision:"verified"},{invocation});reject(seal({...rawObservation,invocationFingerprint:D},"rawObservationDigest"),{invocation});reject(seal({...rawObservation,verifier:{id:"substituted",version:"1.0.0"}},"rawObservationDigest"),{invocation})});
test("observations require typed unique evidence bindings",()=>{const conclusiveWithoutEvidence=seal({...rawObservation,observations:[{obligationId:"OB-AC",status:"pass",evidenceBindings:[]},rawObservation.observations[1]]},"rawObservationDigest");reject(conclusiveWithoutEvidence,{invocation});const binding={kind:"test",artifact:ref("TEST-EVIDENCE")};const duplicateBinding=seal({...rawObservation,observations:[{...rawObservation.observations[0],evidenceBindings:[binding,binding]},rawObservation.observations[1]]},"rawObservationDigest");reject(duplicateBinding,{invocation});const legacy=seal({...rawObservation,observations:[{obligationId:"OB-AC",status:"pass",evidenceArtifacts:[ref("TEST-EVIDENCE")]},rawObservation.observations[1]]},"rawObservationDigest");reject(legacy,{invocation})});
test("rejects unknown fields and stale digests",()=>{reject({...subject,ambientContext:"forbidden"});reject({...subject,subjectId:"changed"});reject({...evaluation,subject:ref("OTHER",subject.subjectDigest)},{subject,obligations,policy,evidence})});
test("resealed evidence and result substitutions fail exact lineage",()=>{reject(seal({...evidence,subject:ref("SUBSTITUTED-SUBJECT",subject.subjectDigest)},"evidenceDigest"),{subject,obligations});reject(seal({...evidence,obligationSet:ref("SUBSTITUTED-OBLIGATIONS",obligations.obligationSetDigest)},"evidenceDigest"),{subject,obligations});for(const field of ["subject","obligationSet","policy","evidence"]){reject(seal({...result,[field]:ref(`SUBSTITUTED-${field.toUpperCase()}`,result[field].digest)},"resultDigest"),{evaluation})}});
test("rejects forbidden authority and invalid outcomes",()=>{reject(seal({...result,authority:"business-acceptance"},"resultDigest"),{evaluation});reject(seal({...evaluation,outcome:"accepted"},"evaluationDigest"),{subject,obligations,policy,evidence});const failed=seal({...evaluation,dispositions:[{obligationId:"OB-AC",status:"failed",evidenceIds:["EV-1"]},{obligationId:"OB-NFR",status:"satisfied",evidenceIds:["EV-2"]}],outcome:"failed"},"evaluationDigest");reject(seal({...result,evaluation:ref(failed.evaluationId,failed.evaluationDigest),outcome:"failed",progression:"business-acceptance-gate"},"resultDigest"),{evaluation:failed})});
test("requires exhaustive criterion and NFR dispositions",()=>{reject(seal({...evaluation,dispositions:evaluation.dispositions.slice(0,1)},"evaluationDigest"),{subject,obligations,policy,evidence});reject(seal({...evaluation,outcome:"failed"},"evaluationDigest"),{subject,obligations,policy,evidence})});
test("module is one-operation provider-neutral and has closed outcomes",()=>{const module=JSON.parse(readFileSync(new URL("../examples/modules/system-verification.module.json",import.meta.url)));assert.equal(documentValidators.moduleDefinition(module),true,JSON.stringify(documentValidators.moduleDefinition.errors));assert.equal(module.operations.length,1);assert.equal(module.operations[0].id,"verify-system");assert.deepEqual(module.operations[0].outcomes,["verified","failed","needs-evidence","baseline-drift","unable-to-proceed"]);assert.equal(module.operations[0].extensionPorts[0].role,"proposer");assert.ok(!JSON.stringify(module).includes("business-acceptance-gate\"}"))});
