import assert from "node:assert/strict";
import test from "node:test";
import { canonicalJson, canonicalJsonDigest } from "../src/content-digest.mjs";
import { createWorkItemVerificationCheckpointController, WorkItemVerificationCheckpointError } from "../src/work-item-verification-checkpoint.mjs";

const D=`sha256:${"a".repeat(64)}`;
const ref=(artifactId,digest=D)=>({artifactId,digest});
const seal=(value,field)=>({...value,[field]:canonicalJsonDigest(Object.fromEntries(Object.entries(value).filter(([key])=>!["apiVersion","kind",field].includes(key))))});
const verifier={id:"verifier.test",version:"1.0.0"};
const assignedObligation={obligationId:"OB-1",kind:"acceptance-criterion",sourceRef:"AC-DEV-WIV-DETERMINISM-001",requiredEvidenceKinds:["test-report"]};
const binding=seal({apiVersion:"devrelay.dev/v1alpha1",kind:"ValidatedVerifierBindingSet",bindingId:"BIND-1",subject:ref("SUB"),obligationSet:ref("OBS"),executorIdentity:"independent",partitions:[{verifier,obligationIds:["OB-1"],permissionDemand:[]}],independence:{required:true,satisfied:true,evidence:ref("I")}},"bindingDigest");
const invocation=(id="VAT-1",workspace="WS",assigned=assignedObligation)=>seal({apiVersion:"devrelay.dev/v1alpha1",kind:"VerifierInvocation",verificationAttemptId:id,subject:ref("SUB"),obligationSet:ref("OBS"),binding:ref("BIND",binding.bindingDigest),verifier,obligationIds:["OB-1"],assignedObligations:[structuredClone(assigned)],candidateWorkspace:ref(workspace),grants:[]},"invocationFingerprint");
const raw=(inv,state="observed")=>{const status=state==="observed"?"pass":state==="failed"?"fail":"inconclusive";const evidenceBindings=status==="inconclusive"?[]:[{evidenceId:`EV-${state.toUpperCase()}`,kind:"test-report",artifact:ref(`REPORT-${state.toUpperCase()}`)}];const observation=seal({observationId:`OBS-${state.toUpperCase()}`,obligationId:"OB-1",status,summary:`verifier ${state}`,evidenceBindings},"observationDigest");return seal({apiVersion:"devrelay.dev/v1alpha1",kind:"RawVerifierResult",verificationAttemptId:inv.verificationAttemptId,invocationFingerprint:inv.invocationFingerprint,bindingDigest:binding.bindingDigest,verifier,terminalState:state,observations:[observation],diagnostics:state==="observed"?[]:[state],nativeArtifacts:[ref(`NATIVE-${state.toUpperCase()}`)]},"rawResultDigest")};
function store(){const values=new Map();return {values,async get(k){return values.get(k)},async put(k,v){if(values.has(k))throw new Error("overwrite");values.set(k,structuredClone(v))}}}

test("returned success, failure, and interruption are checkpointed and replay byte-identically with zero calls",async()=>{for(const state of ["observed","failed","interrupted"]){let calls=0;const inv=invocation(`VAT-${state}`);const bytes=Buffer.from(canonicalJson(raw(inv,state)));const checkpoints=store();const controller=createWorkItemVerificationCheckpointController({verifier:async()=>{calls++;return bytes}});const first=await controller.execute({invocation:inv,binding,checkpoints});const replay=await controller.execute({invocation:inv,binding,checkpoints});assert.equal(calls,1);assert.equal(first.replayed,false);assert.equal(replay.replayed,true);assert.deepEqual(Buffer.from(replay.nativeBytes),bytes)}});
test("thrown failure and interruption are durably checkpointed before surfacing and exact retry makes zero calls",async()=>{for(const [name,code] of [["Error","DR4086"],["AbortError","DR4087"]]){let calls=0;const inv=invocation(`VAT-${name}`);const checkpoints=store();const controller=createWorkItemVerificationCheckpointController({verifier:async()=>{calls++;const error=new Error("stopped");error.name=name;throw error}});await assert.rejects(controller.execute({invocation:inv,binding,checkpoints}),e=>e.code===code);assert.equal(checkpoints.values.size,1);const saved=[...checkpoints.values.values()][0];assert.equal(saved.verificationAttemptId,inv.verificationAttemptId);assert.equal(saved.invocationFingerprint,inv.invocationFingerprint);await assert.rejects(controller.execute({invocation:inv,binding,checkpoints}),e=>e.code===code);assert.equal(calls,1);const replay=await controller.replay({verificationAttemptId:inv.verificationAttemptId,invocationFingerprint:inv.invocationFingerprint,checkpoints});assert.equal(replay.checkpointDigest,saved.checkpointDigest)}});
test("retry has a new identity, retains predecessor, and replays independently",async()=>{let calls=0;const checkpoints=store();const controller=createWorkItemVerificationCheckpointController({verifier:async inv=>{calls++;return raw(inv)}});const first=await controller.execute({invocation:invocation("VAT-1"),binding,checkpoints});const second=await controller.execute({invocation:invocation("VAT-2"),binding,predecessor:first.checkpoint,checkpoints});assert.equal(second.checkpoint.predecessor.checkpointDigest,first.checkpointDigest);await controller.execute({invocation:invocation("VAT-2"),binding,predecessor:first.checkpoint,checkpoints});assert.equal(calls,2);assert.equal(checkpoints.values.size,2)});
test("changed assigned-obligation input, duplicate identity, and predecessor drift fail closed",async()=>{let calls=0;const checkpoints=store();const controller=createWorkItemVerificationCheckpointController({verifier:async inv=>{calls++;return raw(inv)}});const first=await controller.execute({invocation:invocation("VAT-0"),binding,checkpoints});await controller.execute({invocation:invocation("VAT-1"),binding,predecessor:first.checkpoint,checkpoints});const changed={...assignedObligation,requiredEvidenceKinds:["coverage-report"]};await assert.rejects(controller.execute({invocation:invocation("VAT-1","WS",changed),binding,predecessor:first.checkpoint,checkpoints}),WorkItemVerificationCheckpointError);await assert.rejects(controller.execute({invocation:invocation("VAT-1"),binding,checkpoints}),e=>e.code==="DR4085");assert.equal(calls,2)});
test("corrupt predecessor and stored native bytes fail closed",async()=>{const checkpoints=store();const controller=createWorkItemVerificationCheckpointController({verifier:async inv=>raw(inv)});const first=await controller.execute({invocation:invocation("VAT-0"),binding,checkpoints});const drift=structuredClone(first.checkpoint);drift.checkpointDigest=D;await assert.rejects(controller.execute({invocation:invocation("VAT-1"),binding,predecessor:drift,checkpoints}),e=>e.code==="DR4083");const saved=[...checkpoints.values.values()][0];saved.nativeOutput.bytesBase64=Buffer.from("{}").toString("base64");checkpoints.values.set([...checkpoints.values.keys()][0],saved);await assert.rejects(controller.replay({verificationAttemptId:"VAT-0",invocationFingerprint:invocation("VAT-0").invocationFingerprint,checkpoints}),e=>e.code==="DR4083")});
