import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { canonicalJsonDigest } from "../src/content-digest.mjs";
import { documentValidators, validationDetail } from "../src/schema-validation.mjs";
import { validateWorkItemVerificationArtifact, WorkItemVerificationArtifactValidationError } from "../src/work-item-verification-artifact-validator.mjs";

const D=`sha256:${"a".repeat(64)}`, E=`sha256:${"b".repeat(64)}`, CHECKPOINT=`sha256:${"c".repeat(64)}`;
const ref=(artifactId,digest=D)=>({artifactId,digest});
const seal=(value,field)=>({...value,[field]:canonicalJsonDigest(Object.fromEntries(Object.entries(value).filter(([key])=>!["apiVersion","kind",field].includes(key))))});
const sealEvaluation=(value)=>{const material=Object.fromEntries(Object.entries(value).filter(([key])=>!["apiVersion","kind","evaluationId","evaluationDigest"].includes(key)));const withId={...value,evaluationId:`WIVPE-${canonicalJsonDigest(material).slice(7,23).toUpperCase()}`};return seal(withId,"evaluationDigest")};
const sealApproval=(value)=>{const material=Object.fromEntries(Object.entries(value).filter(([key])=>!["apiVersion","kind","approvalId","approvalDigest"].includes(key)));return seal({...value,approvalId:`WIVGA-${canonicalJsonDigest(material).slice(7,23).toUpperCase()}`},"approvalDigest")};
const reject=(value,context)=>assert.throws(()=>validateWorkItemVerificationArtifact(value,context),WorkItemVerificationArtifactValidationError);
const verifier={id:"verifier.test",version:"1.0.0"}, base={apiVersion:"devrelay.dev/v1alpha1"};
const verificationPolicy=seal({...base,kind:"VerificationPolicy",policyId:"POL",version:"1.0.0",evaluationSemantics:"devrelay.work-item-verification/v1",rules:{allObligationsMandatory:true,requiredEvidenceBinding:"explicit-obligation-bound",verifierIndependence:"required",nativeArtifacts:"provenance-only",unknownEvidence:"reject",outcomePrecedence:["failed","needs-evidence","verified"]}},"policyDigest");

const subject=seal({...base,kind:"ValidatedVerificationSubject",subjectId:"SUB",workItemId:"WI-WIV-CONTRACTS",workItem:ref("WI"),executionAttempt:ref("ATT"),changeSetDraft:ref("CHANGE"),executionEvidenceBundle:ref("EXEC-EV"),verificationPolicy:ref("POL",verificationPolicy.policyDigest),requirementsBaseline:ref("REQ"),projectOverviewBaseline:ref("PO"),architectureBaseline:ref("ARCH"),contractDisposition:ref("CD"),workBreakdownBaseline:ref("WBB"),workDependencyBaseline:ref("WDB"),specialistAssignmentBaseline:ref("SAB"),repositoryBase:ref("REPO"),candidateWorkspace:ref("WS")},"subjectDigest");
const obligations=seal({...base,kind:"VerificationObligationSet",obligationSetId:"OBS",subject:ref("SUB",subject.subjectDigest),obligations:[
  {obligationId:"OB-1",kind:"acceptance-criterion",sourceRef:"AC-DEV-WIV-EVIDENCE-001",requiredEvidenceKinds:["test-report","coverage-report"]},
  {obligationId:"OB-2",kind:"work-item-plan",sourceRef:"WI-WIV-CONTRACTS/verification-plan",requiredEvidenceKinds:["review-record"]}
]},"obligationSetDigest");
const binding=seal({...base,kind:"ValidatedVerifierBindingSet",bindingId:"BIND",subject:ref("SUB",subject.subjectDigest),obligationSet:ref("OBS",obligations.obligationSetDigest),executorIdentity:"executor.other",partitions:[{verifier,obligationIds:["OB-1","OB-2"],permissionDemand:[{kind:"process.spawn",values:["node"]}]}],independence:{required:true,satisfied:true,evidence:ref("INDEPENDENCE")}},"bindingDigest");
const invocation=seal({...base,kind:"VerifierInvocation",verificationAttemptId:"VAT-2",subject:ref("SUB",subject.subjectDigest),obligationSet:ref("OBS",obligations.obligationSetDigest),binding:ref("BIND",binding.bindingDigest),verifier,obligationIds:["OB-1","OB-2"],assignedObligations:structuredClone(obligations.obligations),candidateWorkspace:ref("WS"),grants:[{kind:"process.spawn",values:["node"]}]},"invocationFingerprint");
const observation=(value)=>seal(value,"observationDigest");
const observations=[
  observation({observationId:"OBS-1",obligationId:"OB-1",status:"pass",summary:"tests and coverage satisfy the criterion",evidenceBindings:[{evidenceId:"EV-TEST",kind:"test-report",artifact:ref("TEST-LOG")},{evidenceId:"EV-COVERAGE",kind:"coverage-report",artifact:ref("COVERAGE") }]}),
  observation({observationId:"OBS-2",obligationId:"OB-2",status:"pass",summary:"review confirms the plan",evidenceBindings:[{evidenceId:"EV-REVIEW",kind:"review-record",artifact:ref("REVIEW")}]})
];
const raw=seal({...base,kind:"RawVerifierResult",verificationAttemptId:"VAT-2",invocationFingerprint:invocation.invocationFingerprint,bindingDigest:binding.bindingDigest,verifier,terminalState:"observed",observations,diagnostics:[],nativeArtifacts:[ref("NATIVE-LOG")]},"rawResultDigest");
const item=(observation,evidence)=>({evidenceId:evidence.evidenceId,subjectDigest:subject.subjectDigest,observationId:observation.observationId,observationDigest:observation.observationDigest,obligationId:observation.obligationId,kind:evidence.kind,status:observation.status,artifact:evidence.artifact,producer:verifier});
const normalized=seal({...base,kind:"NormalizedVerificationEvidence",normalizedEvidenceId:"EV",verificationAttemptId:"VAT-2",subject:ref("SUB",subject.subjectDigest),invocationFingerprint:invocation.invocationFingerprint,bindingDigest:binding.bindingDigest,checkpointDigest:CHECKPOINT,rawResultDigest:raw.rawResultDigest,collectionTime:{disposition:"timestamp",value:"2026-08-07T18:30:00Z"},nativeArtifacts:[ref("NATIVE-LOG")],items:observations.flatMap((entry)=>entry.evidenceBindings.map((evidence)=>item(entry,evidence)))},"evidenceDigest");
const context={invocation,binding,obligations}, normalizedContext={...context,rawResult:raw,checkpointDigest:CHECKPOINT};
const policy=sealEvaluation({...base,kind:"VerificationPolicyEvaluation",subject:ref("SUB",subject.subjectDigest),obligationSet:ref("OBS",obligations.obligationSetDigest),verificationPolicy:ref("POL",verificationPolicy.policyDigest),verifierBinding:ref("BIND",binding.bindingDigest),normalizedEvidence:ref("EV",normalized.evidenceDigest),outcome:"verified",dispositions:[{obligationId:"OB-1",status:"satisfied",evidenceIds:["EV-TEST","EV-COVERAGE"]},{obligationId:"OB-2",status:"satisfied",evidenceIds:["EV-REVIEW"]}],reasons:[{code:"VERIFIED_ALL_OBLIGATIONS"}]});
const candidate=seal({...base,kind:"WorkItemVerificationGateCandidate",candidateId:"WIVC-2",subject:ref("SUB",subject.subjectDigest),obligationSet:ref("OBS",obligations.obligationSetDigest),verifierBinding:ref("BIND",binding.bindingDigest),normalizedEvidence:ref("EV",normalized.evidenceDigest),policyEvaluation:ref(policy.evaluationId,policy.evaluationDigest),outcome:"verified",authority:"candidate"},"candidateDigest");
const gateApproval=sealApproval({...base,kind:"WorkItemVerificationGateApproval",decision:"approved",candidate:ref("WIVC-2",candidate.candidateDigest),acceptedEvidence:[ref("EV",normalized.evidenceDigest)],acceptanceCriterionIds:["AC-DEV-WIV-EVIDENCE-001"],authority:"work-item-verification-gate"});
const policyContext={policy:verificationPolicy,binding,subject,normalizedEvidence:normalized,obligations};
const candidateContext={policyEvaluation:policy,binding,subject,obligations,normalizedEvidence:normalized};
const candidateTrace=seal({...base,kind:"WorkItemVerificationTraceabilityCandidate",candidate:ref("CAND",candidate.candidateDigest),subject:ref("SUB",subject.subjectDigest),evidence:ref("EV",normalized.evidenceDigest),authority:"candidate",scope:"work-item-verification/candidate"},"traceabilityDigest");
const approvedTrace=seal({...base,kind:"ApprovedWorkItemVerificationTraceability",gateApproval:ref(gateApproval.approvalId,gateApproval.approvalDigest),candidate:ref("CAND",candidate.candidateDigest),acceptedEvidence:[ref("EV",normalized.evidenceDigest)],acceptanceCriterionIds:["AC-DEV-WIV-EVIDENCE-001"],authority:"approved",scope:"work-item-verification/approved"},"traceabilityDigest");

test("attempt 5 accepts two obligations with distinct explicit evidence and separate native provenance",()=>{for(const value of [verificationPolicy,subject,obligations,binding,invocation,candidateTrace,approvedTrace])assert.equal(validateWorkItemVerificationArtifact(value),value);assert.equal(validateWorkItemVerificationArtifact(raw,context),raw);assert.equal(validateWorkItemVerificationArtifact(normalized,normalizedContext),normalized);assert.equal(validateWorkItemVerificationArtifact(policy,policyContext),policy);assert.equal(validateWorkItemVerificationArtifact(candidate,candidateContext),candidate);assert.equal(validateWorkItemVerificationArtifact(gateApproval,{candidate,normalizedEvidence:normalized,obligations}),gateApproval);assert.deepEqual(normalized.items.filter(({obligationId})=>obligationId==="OB-1").map(({artifact})=>artifact.artifactId),["TEST-LOG","COVERAGE"]);assert.deepEqual(normalized.items.filter(({obligationId})=>obligationId==="OB-2").map(({artifact})=>artifact.artifactId),["REVIEW"]);assert.equal(normalized.items.some(({artifact})=>artifact.artifactId==="NATIVE-LOG"),false)});
test("Gate approval is affirmative, deterministic, exact, and rejects substitutions",()=>{assert.match(gateApproval.approvalId,/^WIVGA-[0-9A-F]{16}$/);for(const changed of [sealApproval({...gateApproval,candidate:ref("OTHER")}),sealApproval({...gateApproval,acceptedEvidence:[ref("OTHER")]}),sealApproval({...gateApproval,acceptanceCriterionIds:["AC-OTHER"]}),{...gateApproval,decision:"rejected"},{...gateApproval,authority:"caller"}])reject(changed,{candidate,normalizedEvidence:normalized,obligations})});
test("collection time is a closed supplied timestamp or not-applicable disposition",()=>{const notApplicable=seal({...normalized,collectionTime:{disposition:"not-applicable",rationale:"Source verifier does not expose collection time"}},"evidenceDigest");assert.equal(validateWorkItemVerificationArtifact(notApplicable,normalizedContext),notApplicable);for(const collectionTime of [{disposition:"timestamp"},{disposition:"timestamp",value:"now"},{disposition:"not-applicable"},{disposition:"generated",value:"2026-08-07T18:30:00Z"}])reject(seal({...normalized,collectionTime},"evidenceDigest"),normalizedContext)});
test("raw observations reject missing, duplicate, unrelated, or unbound evidence",()=>{const rawWith=(next)=>seal({...raw,observations:next},"rawResultDigest");reject(rawWith([observation({...observations[0],evidenceBindings:[]})]),context);const duplicate=structuredClone(observations);duplicate[1].evidenceBindings[0].evidenceId="EV-TEST";duplicate[1]=observation(duplicate[1]);reject(rawWith(duplicate),context);const unrelated=[observation({...observations[0],evidenceBindings:[{evidenceId:"EV-X",kind:"review-record",artifact:ref("REVIEW")} ]})];reject(rawWith(unrelated),context);const unbound=[observation({...observations[0],obligationId:"OB-UNKNOWN"})];reject(rawWith(unbound),context)});
test("pass requires every required evidence kind while inconclusive may explicitly lack proof",()=>{const partial=[observation({...observations[0],evidenceBindings:[observations[0].evidenceBindings[0]]}),observations[1]];reject(seal({...raw,observations:partial},"rawResultDigest"),context);const inconclusive=[observation({observationId:"OBS-I",obligationId:"OB-1",status:"inconclusive",summary:"coverage report missing",evidenceBindings:[]}),observations[1]];assert.equal(validateWorkItemVerificationArtifact(seal({...raw,observations:inconclusive},"rawResultDigest"),context).observations[0].status,"inconclusive")});
test("inconclusive or unrelated evidence cannot satisfy policy or a verified Gate candidate",()=>{const incomplete=seal({...normalized,items:normalized.items.filter(({evidenceId})=>evidenceId!=="EV-COVERAGE")},"evidenceDigest");reject(policy,{...policyContext,normalizedEvidence:incomplete});const needsEvidence=sealEvaluation({...policy,normalizedEvidence:ref("EV",incomplete.evidenceDigest),outcome:"needs-evidence",dispositions:[{obligationId:"OB-1",status:"needs-evidence",evidenceIds:["EV-TEST"]},{obligationId:"OB-2",status:"satisfied",evidenceIds:["EV-REVIEW"]}],reasons:[{code:"OBLIGATION_NEEDS_EVIDENCE",obligationId:"OB-1"}]});assert.equal(validateWorkItemVerificationArtifact(needsEvidence,{...policyContext,normalizedEvidence:incomplete}),needsEvidence);reject(candidate,{...candidateContext,policyEvaluation:needsEvidence})});
test("normalization preserves one-to-one bindings and exact invocation, checkpoint, raw result, and provenance",()=>{const swap=structuredClone(normalized);swap.items[0].obligationId="OB-2";reject(seal(swap,"evidenceDigest"),normalizedContext);const missing=structuredClone(normalized);missing.items.pop();reject(seal(missing,"evidenceDigest"),normalizedContext);const duplicate=structuredClone(normalized);duplicate.items[1].evidenceId=duplicate.items[0].evidenceId;reject(seal(duplicate,"evidenceDigest"),normalizedContext);for(const [field,value] of [["invocationFingerprint",E],["bindingDigest",E],["checkpointDigest",E],["rawResultDigest",E]])reject(seal({...normalized,[field]:value},"evidenceDigest"),normalizedContext);reject(seal({...normalized,nativeArtifacts:[ref("OTHER-NATIVE")]},"evidenceDigest"),normalizedContext)});
test("raw validation requires the exact obligation set, subject, and verifier partition",()=>{const coincident=seal({...obligations,obligations:obligations.obligations.map((entry)=>({...entry,sourceRef:`wrong/${entry.sourceRef}`}))},"obligationSetDigest");reject(raw,{invocation,binding,obligations:coincident});reject(raw,{invocation,binding:{...binding,subject:ref("OTHER-SUBJECT")},obligations});reject(raw,{invocation,binding:{...binding,partitions:[{...binding.partitions[0],obligationIds:["OB-1"]}]},obligations});const otherInvocation=seal({...invocation,binding:ref("OTHER-BINDING",E)},"invocationFingerprint");const otherRaw=seal({...raw,invocationFingerprint:otherInvocation.invocationFingerprint},"rawResultDigest");reject(otherRaw,{invocation:otherInvocation,binding,obligations})});
test("raw result contains exactly one disposition for every assigned obligation",()=>{reject(seal({...raw,observations:[observations[0]]},"rawResultDigest"),context);const duplicateObligation=[observations[0],observation({...observations[1],observationId:"OBS-3",obligationId:"OB-1",evidenceBindings:[{evidenceId:"EV-OTHER",kind:"test-report",artifact:ref("OTHER")}]})];reject(seal({...raw,observations:duplicateObligation},"rawResultDigest"),context);const outside=[observations[0],observation({...observations[1],obligationId:"OB-OUTSIDE"})];reject(seal({...raw,observations:outside},"rawResultDigest"),context)});
test("normalized subject must be the exact subject shared by invocation, binding, and obligations",()=>{const forgedSubject=ref("FORGED-SUBJECT",E);const forged=seal({...normalized,subject:forgedSubject,items:normalized.items.map((entry)=>({...entry,subjectDigest:E}))},"evidenceDigest");reject(forged,normalizedContext)});
test("policy rejects unresolved and foreign obligation evidence identities",()=>{const unresolved=sealEvaluation({...policy,dispositions:policy.dispositions.map((entry,index)=>index===0?{...entry,evidenceIds:[...entry.evidenceIds,"EV-MISSING"]}:entry)});reject(unresolved,policyContext);const foreign=sealEvaluation({...policy,dispositions:policy.dispositions.map((entry,index)=>index===0?{...entry,evidenceIds:[...entry.evidenceIds,"EV-REVIEW"]}:entry)});reject(foreign,policyContext)});
test("unknown fields, canonical drift, adapter substitution, and lifecycle authority fail closed",()=>{for(const [value,ctx] of [[raw,context],[normalized,normalizedContext],[candidate,candidateContext]])reject({...value,unknown:true},ctx);for(const [value,ctx,field] of [[raw,context,"rawResultDigest"],[normalized,normalizedContext,"evidenceDigest"],[candidate,candidateContext,"candidateDigest"]])reject({...value,[field]:E},ctx);reject({...raw,verifier:{id:"verifier.other",version:"1.0.0"}},{...context});for(const field of ["verified","completed","integrated","graphMutation","policyOutcome"])reject({...raw,[field]:true},context)});
test("module remains provider-neutral with a proposer-only verifier port",()=>{const module=JSON.parse(readFileSync(new URL("../examples/modules/work-item-verification.module.json",import.meta.url)));assert.equal(documentValidators.moduleDefinition(module),true,validationDetail(documentValidators.moduleDefinition));assert.deepEqual(module.operations[0].extensionPorts,[{id:"verifier",role:"proposer",inputSchema:"https://devrelay.dev/artifacts/verifier-invocation/v1",outputSchema:"https://devrelay.dev/artifacts/raw-verifier-result/v1",required:true}]);const text=JSON.stringify(module).toLowerCase();for(const forbidden of ["openai","anthropic","graphmutation","integratedcompletionfact"])assert.equal(text.includes(forbidden),false,forbidden)});
test("attempt 3 raw adapter and checkpoint boundary is self-contained",()=>{assert.equal(validateWorkItemVerificationArtifact(raw,{invocation,binding}),raw);const missing=seal({...invocation,assignedObligations:[invocation.assignedObligations[0]]},"invocationFingerprint");const missingRaw=seal({...raw,invocationFingerprint:missing.invocationFingerprint},"rawResultDigest");reject(missingRaw,{invocation:missing,binding});const changed=seal({...invocation,assignedObligations:invocation.assignedObligations.map((entry,index)=>index===0?{...entry,requiredEvidenceKinds:["other-kind"]}:entry)},"invocationFingerprint");const changedRaw=seal({...raw,invocationFingerprint:changed.invocationFingerprint},"rawResultDigest");reject(changedRaw,{invocation:changed,binding,obligations})});
test("attempt 4 canonical-sorts native provenance while preserving the exact multiset",()=>{const nativeA=ref("A-NATIVE"),nativeB=ref("B-NATIVE"),nativeC=ref("C-NATIVE");const reorderedRaw=seal({...raw,nativeArtifacts:[nativeC,nativeA,nativeB]},"rawResultDigest");const canonical=seal({...normalized,rawResultDigest:reorderedRaw.rawResultDigest,nativeArtifacts:[nativeA,nativeB,nativeC]},"evidenceDigest");const reorderedContext={...normalizedContext,rawResult:reorderedRaw};assert.equal(validateWorkItemVerificationArtifact(canonical,reorderedContext),canonical);for(const nativeArtifacts of [[nativeA,nativeB],[nativeA,nativeB,nativeC,ref("D-NATIVE")],[nativeA,nativeB,nativeB,nativeC],[nativeA,nativeB,ref("X-NATIVE")],[nativeC,nativeA,nativeB]])reject(seal({...canonical,nativeArtifacts},"evidenceDigest"),reorderedContext)});
test("attempt 5 policy is version-pinned, canonical, provider-neutral, and exactly subject-bound",()=>{assert.equal(validateWorkItemVerificationArtifact(verificationPolicy),verificationPolicy);reject({...verificationPolicy,policyDigest:E});reject(seal({...verificationPolicy,version:"2.0.0"},"policyDigest"));reject(seal({...verificationPolicy,evaluationSemantics:"other/v1"},"policyDigest"));reject(seal({...verificationPolicy,rules:{...verificationPolicy.rules,nativeArtifacts:"evidence"}},"policyDigest"));const changed=seal({...verificationPolicy,rules:{...verificationPolicy.rules,verifierIndependence:"optional"}},"policyDigest");reject(policy,{...policyContext,policy:changed})});
test("attempt 5 derives failed and needs-evidence with deterministic precedence and complete reasons",()=>{const failedEvidence=seal({...normalized,items:normalized.items.map((entry)=>entry.evidenceId==="EV-TEST"?{...entry,status:"fail"}:entry)},"evidenceDigest");const failed=sealEvaluation({...policy,normalizedEvidence:ref("EV",failedEvidence.evidenceDigest),outcome:"failed",dispositions:[{obligationId:"OB-2",status:"satisfied",evidenceIds:["EV-REVIEW"]},{obligationId:"OB-1",status:"failed",evidenceIds:["EV-TEST","EV-COVERAGE"]}],reasons:[{code:"OBLIGATION_FAILED",obligationId:"OB-1"}]});assert.equal(validateWorkItemVerificationArtifact(failed,{...policyContext,normalizedEvidence:failedEvidence}),failed);reject(sealEvaluation({...failed,outcome:"needs-evidence",reasons:[{code:"OBLIGATION_NEEDS_EVIDENCE",obligationId:"OB-1"}]}),{...policyContext,normalizedEvidence:failedEvidence});reject(sealEvaluation({...failed,reasons:[{code:"OBLIGATION_FAILED",obligationId:"OB-2"}]}),{...policyContext,normalizedEvidence:failedEvidence})});
test("attempt 5 enforces required, unsatisfied, and optional independence",()=>{const unsatisfiedBinding=seal({...binding,independence:{...binding.independence,satisfied:false}},"bindingDigest");const independenceFailure=sealEvaluation({...policy,verifierBinding:ref("BIND",unsatisfiedBinding.bindingDigest),outcome:"failed",reasons:[{code:"INDEPENDENCE_REQUIRED_UNSATISFIED"}]});assert.equal(validateWorkItemVerificationArtifact(independenceFailure,{...policyContext,binding:unsatisfiedBinding}),independenceFailure);reject(policy,{...policyContext,binding:unsatisfiedBinding});const optionalPolicy=seal({...verificationPolicy,rules:{...verificationPolicy.rules,verifierIndependence:"optional"}},"policyDigest");const optionalSubject=seal({...subject,verificationPolicy:ref("POL",optionalPolicy.policyDigest)},"subjectDigest");const optionalObligations=seal({...obligations,subject:ref("SUB",optionalSubject.subjectDigest)},"obligationSetDigest");const optionalBinding=seal({...binding,subject:ref("SUB",optionalSubject.subjectDigest),obligationSet:ref("OBS",optionalObligations.obligationSetDigest),independence:{...binding.independence,required:false,satisfied:false}},"bindingDigest");const optionalNormalized=seal({...normalized,subject:ref("SUB",optionalSubject.subjectDigest),bindingDigest:optionalBinding.bindingDigest,items:normalized.items.map((entry)=>({...entry,subjectDigest:optionalSubject.subjectDigest}))},"evidenceDigest");const optionalEvaluation=sealEvaluation({...policy,subject:ref("SUB",optionalSubject.subjectDigest),obligationSet:ref("OBS",optionalObligations.obligationSetDigest),verificationPolicy:ref("POL",optionalPolicy.policyDigest),verifierBinding:ref("BIND",optionalBinding.bindingDigest),normalizedEvidence:ref("EV",optionalNormalized.evidenceDigest)});assert.equal(validateWorkItemVerificationArtifact(optionalEvaluation,{policy:optionalPolicy,subject:optionalSubject,obligations:optionalObligations,binding:optionalBinding,normalizedEvidence:optionalNormalized}),optionalEvaluation)});
test("attempt 6 keeps baseline-drift and unable-to-proceed before evaluation with no candidate",()=>{for(const outcome of ["baseline-drift","unable-to-proceed"]){reject(seal({...policy,outcome},"evaluationDigest"),policyContext);reject(seal({...candidate,outcome},"candidateDigest"),candidateContext)}reject(seal({...policy,evaluationCondition:"required-capability-unavailable"},"evaluationDigest"),policyContext);const module=JSON.parse(readFileSync(new URL("../examples/modules/work-item-verification.module.json",import.meta.url)));for(const outcome of ["baseline-drift","unable-to-proceed"]){assert.ok(module.operations[0].outcomes.includes(outcome));assert.deepEqual(module.operations[0].resultContracts[outcome].requiredOutputs,[]);assert.deepEqual(module.operations[0].resultContracts[outcome].allowedOutputs,[])}});
test("attempt 5 candidate preserves every exact evaluation input and rejects substitution",()=>{assert.equal(validateWorkItemVerificationArtifact(candidate,candidateContext),candidate);for(const field of ["subject","obligationSet","verifierBinding","normalizedEvidence","policyEvaluation"])reject(seal({...candidate,[field]:ref(`OTHER-${field}`,E)},"candidateDigest"),candidateContext);const failedEvaluation=seal({...policy,outcome:"failed",reasons:[{code:"INDEPENDENCE_REQUIRED_UNSATISFIED"}]},"evaluationDigest");reject(candidate,{...candidateContext,policyEvaluation:failedEvaluation})});
test("revision attempt 007 binds deterministic evaluation identity and exact candidate reference",()=>{assert.match(policy.evaluationId,/^WIVPE-[0-9A-F]{16}$/);reject({...policy,evaluationId:"caller-selected"},policyContext);reject(seal({...policy,evaluationId:"WIVPE-0000000000000000"},"evaluationDigest"),policyContext);const digestOnlySubstitution=seal({...candidate,policyEvaluation:ref("WIVPE-FFFFFFFFFFFFFFFF",policy.evaluationDigest)},"candidateDigest");reject(digestOnlySubstitution,candidateContext);const changedEvaluation=sealEvaluation({...policy,reasons:[{code:"VERIFIED_ALL_OBLIGATIONS"}],dispositions:[...policy.dispositions].reverse()});assert.notEqual(changedEvaluation.evaluationId,policy.evaluationId);assert.notEqual(changedEvaluation.evaluationDigest,policy.evaluationDigest);reject(candidate,{...candidateContext,policyEvaluation:changedEvaluation});const stalePair=seal({...candidate,policyEvaluation:ref(policy.evaluationId,policy.evaluationDigest)},"candidateDigest");reject(stalePair,{...candidateContext,policyEvaluation:changedEvaluation})});
