import assert from "node:assert/strict";
import test from "node:test";
import { canonicalJson, canonicalJsonDigest, sha256Digest } from "../src/content-digest.mjs";
import { normalizeWorkItemVerificationEvidence, WorkItemVerificationEvidenceNormalizationError } from "../src/work-item-verification-evidence-normalizer.mjs";

const D=`sha256:${"a".repeat(64)}`, ref=(artifactId,digest=D)=>({artifactId,digest});
const seal=(value,field)=>({...value,[field]:canonicalJsonDigest(Object.fromEntries(Object.entries(value).filter(([key])=>!["apiVersion","kind",field].includes(key))))});
const observation=(value)=>seal(value,"observationDigest"), verifier={id:"verifier.test",version:"1.0.0"};
function fixture({reverse=false,inconclusive=false}={}){
 const subject=seal({apiVersion:"devrelay.dev/v1alpha1",kind:"ValidatedVerificationSubject",subjectId:"SUB-1",workItemId:"WI-WIV-EVIDENCE-NORMALIZATION",workItem:ref("WI"),executionAttempt:ref("ATT"),changeSetDraft:ref("CHANGE"),executionEvidenceBundle:ref("EXEC"),verificationPolicy:ref("POL"),requirementsBaseline:ref("REQ"),projectOverviewBaseline:ref("PO"),architectureBaseline:ref("ARCH"),contractDisposition:ref("CD"),workBreakdownBaseline:ref("WBB"),workDependencyBaseline:ref("WDB"),specialistAssignmentBaseline:ref("SAB"),repositoryBase:ref("REPO"),candidateWorkspace:ref("WS")},"subjectDigest"), sr=ref(subject.subjectId,subject.subjectDigest);
 const duties=[{obligationId:"OB-1",kind:"acceptance-criterion",sourceRef:"AC-1",requiredEvidenceKinds:["test-report","coverage-report"]},{obligationId:"OB-2",kind:"contract",sourceRef:"CT-1",requiredEvidenceKinds:["review-record"]}];
 const obligationSet=seal({apiVersion:"devrelay.dev/v1alpha1",kind:"VerificationObligationSet",obligationSetId:"OBSET-WIV-EVIDENCE-NORMALIZATION",subject:sr,obligations:duties},"obligationSetDigest"), obligationSetRef=ref(obligationSet.obligationSetId,obligationSet.obligationSetDigest);
 const binding=seal({apiVersion:"devrelay.dev/v1alpha1",kind:"ValidatedVerifierBindingSet",bindingId:"BIND",subject:sr,obligationSet:obligationSetRef,executorIdentity:"other",partitions:[{verifier,obligationIds:["OB-1","OB-2"],permissionDemand:[]}],independence:{required:true,satisfied:true,evidence:ref("IND")}},"bindingDigest");
 const invocation=seal({apiVersion:"devrelay.dev/v1alpha1",kind:"VerifierInvocation",verificationAttemptId:"VAT-2",subject:sr,obligationSet:obligationSetRef,binding:ref("BIND",binding.bindingDigest),verifier,obligationIds:["OB-1","OB-2"],assignedObligations:duties,candidateWorkspace:ref("WS"),grants:[]},"invocationFingerprint");
 let observations=[observation({observationId:"OBS-1",obligationId:"OB-1",status:inconclusive?"inconclusive":"pass",summary:"machine result",evidenceBindings:inconclusive?[]:[{evidenceId:"EV-TEST",kind:"test-report",artifact:ref("TEST-ART")},{evidenceId:"EV-COVERAGE",kind:"coverage-report",artifact:ref("COVERAGE-ART")}]}),observation({observationId:"OBS-2",obligationId:"OB-2",status:"fail",summary:"review result",evidenceBindings:[{evidenceId:"EV-REVIEW",kind:"review-record",artifact:ref("REVIEW-ART")} ]})];
 if(reverse){observations=observations.reverse().map(entry=>{const {observationDigest:_,...body}=entry;return observation({...body,evidenceBindings:[...body.evidenceBindings].reverse()});});}
 const rawBody={apiVersion:"devrelay.dev/v1alpha1",kind:"RawVerifierResult",verificationAttemptId:"VAT-2",invocationFingerprint:invocation.invocationFingerprint,bindingDigest:binding.bindingDigest,verifier,terminalState:"observed",observations,diagnostics:[],nativeArtifacts:[ref("NATIVE-A"),ref("NATIVE-B")]};
 const raw=seal(rawBody,"rawResultDigest"), bytes=Buffer.from(canonicalJson(raw));
 const checkpointBody={apiVersion:"devrelay.dev/v1alpha1",kind:"VerificationAttemptCheckpoint",verificationAttemptId:"VAT-2",invocationFingerprint:invocation.invocationFingerprint,invocation,binding,terminalState:"returned",nativeOutput:{digest:sha256Digest(bytes),bytesBase64:bytes.toString("base64")}};
 const checkpoint={...checkpointBody,checkpointDigest:canonicalJsonDigest(checkpointBody)};
 return {subject,obligationSet,binding,invocation,replay:{replayed:true,checkpointDigest:checkpoint.checkpointDigest,checkpoint,nativeBytes:bytes,rawResult:raw},collectionTime:{disposition:"timestamp",value:"2026-08-07T18:30:00Z"},normalizedEvidenceId:"NVE-WIV-EVIDENCE-NORMALIZATION-VAT-2"};
}
const reject=(input,pattern)=>assert.throws(()=>normalizeWorkItemVerificationEvidence(input),error=>error instanceof WorkItemVerificationEvidenceNormalizationError&&pattern.test(error.message));

test("preserves distinct explicit artifacts, multiple kinds, lineage, and separated native provenance",()=>{const input=fixture(), out=normalizeWorkItemVerificationEvidence(input);assert.deepEqual(out.items.map(({evidenceId})=>evidenceId),["EV-COVERAGE","EV-REVIEW","EV-TEST"]);assert.deepEqual(out.items.map(({artifact})=>artifact.artifactId),["COVERAGE-ART","REVIEW-ART","TEST-ART"]);assert.deepEqual(out.nativeArtifacts.map(({artifactId})=>artifactId),["NATIVE-A","NATIVE-B"]);assert.ok(out.items.every(({artifact})=>!artifact.artifactId.startsWith("NATIVE")));assert.equal(out.invocationFingerprint,input.invocation.invocationFingerprint);assert.equal(out.checkpointDigest,input.replay.checkpointDigest);assert.equal(out.rawResultDigest,input.replay.rawResult.rawResultDigest);});
test("explicit inconclusive observation emits zero proving items",()=>{const out=normalizeWorkItemVerificationEvidence(fixture({inconclusive:true}));assert.equal(out.items.some(({obligationId})=>obligationId==="OB-1"),false);assert.equal(out.items.length,1);});
test("reordered raw observation and evidence-binding arrays canonicalize item ordering",()=>{const a=normalizeWorkItemVerificationEvidence(fixture()),b=normalizeWorkItemVerificationEvidence(fixture({reverse:true}));assert.deepEqual(a.items.map(({evidenceId})=>evidenceId),b.items.map(({evidenceId})=>evidenceId));assert.deepEqual(a.items.map(({artifact})=>artifact),b.items.map(({artifact})=>artifact));assert.notEqual(a.rawResultDigest,b.rawResultDigest);});
test("timestamp and not-applicable collection dispositions are supplied, closed, and deterministic",()=>{const input=fixture(),a=normalizeWorkItemVerificationEvidence(input),b=normalizeWorkItemVerificationEvidence(input);assert.equal(a.evidenceDigest,b.evidenceDigest);input.collectionTime={disposition:"not-applicable",rationale:"Verifier provides no meaningful collection time."};assert.equal(normalizeWorkItemVerificationEvidence(input).collectionTime.disposition,"not-applicable");for(const collectionTime of [undefined,{disposition:"timestamp",value:"now"},{disposition:"generated",value:"2026-08-07T18:30:00Z"}])reject({...fixture(),collectionTime},/collectionTime|normalized evidence is invalid/);});
test("non-replay, forged bytes, stale checkpoint, and mismatched replay object fail closed",()=>{let input=fixture();input.replay.replayed=false;reject(input,/replay/);input=fixture();input.replay.nativeBytes=Buffer.from("{}");reject(input,/forged|stale/);input=fixture();input.replay.checkpointDigest=D;reject(input,/checkpoint replay/);input=fixture();input.replay.rawResult={...input.replay.rawResult,diagnostics:["forged"]};reject(input,/differs/);});
test("wrong subject, stale obligation context, and mismatched assigned slice fail closed",()=>{let input=fixture();input.subject={...input.subject,subjectId:"OTHER"};reject(input,/invalid|subject/);input=fixture();input.obligationSet={...input.obligationSet,obligationSetDigest:D};reject(input,/invalid|stale/);input=fixture();input.invocation.assignedObligations=input.invocation.assignedObligations.slice(0,1);reject(input,/invalid|assigned/);});
test("obligation-set identity cannot be substituted while retaining its digest",()=>{for(const target of ["binding","invocation"]){const input=fixture(),body={...input[target],obligationSet:{...input[target].obligationSet,artifactId:"OBSET-SUBSTITUTED"}};delete body[target==="binding"?"bindingDigest":"invocationFingerprint"];input[target]=seal(body,target==="binding"?"bindingDigest":"invocationFingerprint");reject(input,/substituted obligation set/);}});
test("duplicate, crossed, unrelated, or missing explicit bindings fail closed",()=>{for(const mutate of [raw=>raw.observations[1].evidenceBindings[0].evidenceId="EV-TEST",raw=>raw.observations[0].evidenceBindings[0].kind="review-record",raw=>raw.observations[0].evidenceBindings.pop(),raw=>raw.observations.push({...raw.observations[0],observationId:"OBS-X"})]){const input=fixture(),raw=structuredClone(input.replay.rawResult);mutate(raw);delete raw.rawResultDigest;const sealed=seal(raw,"rawResultDigest"),bytes=Buffer.from(canonicalJson(sealed));input.replay.rawResult=sealed;input.replay.nativeBytes=bytes;input.replay.checkpoint.nativeOutput={digest:sha256Digest(bytes),bytesBase64:bytes.toString("base64")};delete input.replay.checkpoint.checkpointDigest;input.replay.checkpoint.checkpointDigest=canonicalJsonDigest(input.replay.checkpoint);input.replay.checkpointDigest=input.replay.checkpoint.checkpointDigest;reject(input,/invalid|duplicate|evidence|observation/);}});
