import assert from "node:assert/strict";
import test from "node:test";
import { canonicalJson, canonicalJsonDigest, sha256Digest } from "../src/content-digest.mjs";
import { createInMemoryTraceabilityStore, createTraceabilityGraphService } from "../src/traceability-graph.mjs";
import { workItemVerificationApprovedTraceabilityContributor, workItemVerificationCandidateTraceabilityContributor } from "../src/work-item-verification-traceability-contributor.mjs";
import { approveWorkItemVerification } from "../src/work-item-verification-gate.mjs";

const D=`sha256:${"a".repeat(64)}`, CHECKPOINT=`sha256:${"c".repeat(64)}`, base={apiVersion:"devrelay.dev/v1alpha1"}, verifier={id:"verifier.test",version:"1.0.0"};
const ref=(artifactId,digest=D)=>({artifactId,digest});
const seal=(value,field)=>({...value,[field]:canonicalJsonDigest(Object.fromEntries(Object.entries(value).filter(([key])=>!["apiVersion","kind",field].includes(key))))});
const sealEvaluation=(value)=>{const material=Object.fromEntries(Object.entries(value).filter(([key])=>!["apiVersion","kind","evaluationId","evaluationDigest"].includes(key)));return seal({...value,evaluationId:`WIVPE-${canonicalJsonDigest(material).slice(7,23).toUpperCase()}`},"evaluationDigest")};
function fixture() {
  const policyArtifact=seal({...base,kind:"VerificationPolicy",policyId:"POL",version:"1.0.0",evaluationSemantics:"devrelay.work-item-verification/v1",rules:{allObligationsMandatory:true,requiredEvidenceBinding:"explicit-obligation-bound",verifierIndependence:"required",nativeArtifacts:"provenance-only",unknownEvidence:"reject",outcomePrecedence:["failed","needs-evidence","verified"]}},"policyDigest");
  const subject=seal({...base,kind:"ValidatedVerificationSubject",subjectId:"SUB",workItemId:"WI-WIV-TRACEABILITY",workItem:ref("WI-WIV-TRACEABILITY"),executionAttempt:ref("ATT"),changeSetDraft:ref("CHANGE"),executionEvidenceBundle:ref("EXEC"),verificationPolicy:ref("POL",policyArtifact.policyDigest),requirementsBaseline:ref("REQ"),projectOverviewBaseline:ref("PO"),architectureBaseline:ref("ARCH"),contractDisposition:ref("CD"),workBreakdownBaseline:ref("WBB"),workDependencyBaseline:ref("WDB"),specialistAssignmentBaseline:ref("SAB"),repositoryBase:ref("REPO"),candidateWorkspace:ref("WS")},"subjectDigest");
  const obligations=seal({...base,kind:"VerificationObligationSet",obligationSetId:"OBS",subject:ref("SUB",subject.subjectDigest),obligations:[{obligationId:"OB-AC",kind:"acceptance-criterion",sourceRef:"AC-DEV-WIV-TRACEABILITY-001",requiredEvidenceKinds:["test-report"]},{obligationId:"OB-WI",kind:"work-item-plan",sourceRef:"WI-WIV-TRACEABILITY/verification-plan",requiredEvidenceKinds:["review-record"]}]},"obligationSetDigest");
  const binding=seal({...base,kind:"ValidatedVerifierBindingSet",bindingId:"BIND",subject:ref("SUB",subject.subjectDigest),obligationSet:ref("OBS",obligations.obligationSetDigest),executorIdentity:"executor.other",partitions:[{verifier,obligationIds:["OB-AC","OB-WI"],permissionDemand:[{kind:"process.spawn",values:["node"]}]}],independence:{required:true,satisfied:true,evidence:ref("IND")}},"bindingDigest");
  const invocation=seal({...base,kind:"VerifierInvocation",verificationAttemptId:"VAT-TRACE",subject:ref("SUB",subject.subjectDigest),obligationSet:ref("OBS",obligations.obligationSetDigest),binding:ref("BIND",binding.bindingDigest),verifier,obligationIds:["OB-AC","OB-WI"],assignedObligations:structuredClone(obligations.obligations),candidateWorkspace:ref("WS"),grants:[{kind:"process.spawn",values:["node"]}]},"invocationFingerprint");
  const observation=(value)=>seal(value,"observationDigest");
  const observations=[observation({observationId:"O-AC",obligationId:"OB-AC",status:"pass",summary:"criterion observed",evidenceBindings:[{evidenceId:"EV-AC",kind:"test-report",artifact:ref("TEST") }]}),observation({observationId:"O-WI",obligationId:"OB-WI",status:"pass",summary:"work item reviewed",evidenceBindings:[{evidenceId:"EV-WI",kind:"review-record",artifact:ref("REVIEW")}]})];
  const raw=seal({...base,kind:"RawVerifierResult",verificationAttemptId:"VAT-TRACE",invocationFingerprint:invocation.invocationFingerprint,bindingDigest:binding.bindingDigest,verifier,terminalState:"observed",observations,diagnostics:[],nativeArtifacts:[]},"rawResultDigest");
  const items=observations.map((observation)=>{const evidence=observation.evidenceBindings[0];return {evidenceId:evidence.evidenceId,subjectDigest:subject.subjectDigest,observationId:observation.observationId,observationDigest:observation.observationDigest,obligationId:observation.obligationId,kind:evidence.kind,status:observation.status,artifact:evidence.artifact,producer:verifier}});
  const evidence=seal({...base,kind:"NormalizedVerificationEvidence",normalizedEvidenceId:"NVE",verificationAttemptId:"VAT-TRACE",subject:ref("SUB",subject.subjectDigest),invocationFingerprint:invocation.invocationFingerprint,bindingDigest:binding.bindingDigest,checkpointDigest:CHECKPOINT,rawResultDigest:raw.rawResultDigest,collectionTime:{disposition:"timestamp",value:"2026-08-07T18:30:00Z"},nativeArtifacts:[],items},"evidenceDigest");
  const evaluation=sealEvaluation({...base,kind:"VerificationPolicyEvaluation",subject:ref("SUB",subject.subjectDigest),obligationSet:ref("OBS",obligations.obligationSetDigest),verificationPolicy:ref("POL",policyArtifact.policyDigest),verifierBinding:ref("BIND",binding.bindingDigest),normalizedEvidence:ref("NVE",evidence.evidenceDigest),outcome:"verified",dispositions:[{obligationId:"OB-AC",status:"satisfied",evidenceIds:["EV-AC"]},{obligationId:"OB-WI",status:"satisfied",evidenceIds:["EV-WI"]}],reasons:[{code:"VERIFIED_ALL_OBLIGATIONS"}]});
  const candidate=seal({...base,kind:"WorkItemVerificationGateCandidate",candidateId:"WIVC-TRACE",subject:ref("SUB",subject.subjectDigest),obligationSet:ref("OBS",obligations.obligationSetDigest),verifierBinding:ref("BIND",binding.bindingDigest),normalizedEvidence:ref("NVE",evidence.evidenceDigest),policyEvaluation:ref(evaluation.evaluationId,evaluation.evaluationDigest),outcome:"verified",authority:"candidate"},"candidateDigest");
  const candidateTrace=seal({...base,kind:"WorkItemVerificationTraceabilityCandidate",candidate:ref("WIVC-TRACE",candidate.candidateDigest),subject:ref("SUB",subject.subjectDigest),evidence:ref("NVE",evidence.evidenceDigest),authority:"candidate",scope:"work-item-verification/candidate"},"traceabilityDigest");
  const gateApproval=approveWorkItemVerification({candidate,normalizedEvidence:evidence,obligationSet:obligations});
  const approvedTrace=seal({...base,kind:"ApprovedWorkItemVerificationTraceability",gateApproval:ref(gateApproval.approvalId,gateApproval.approvalDigest),candidate:ref("WIVC-TRACE",candidate.candidateDigest),acceptedEvidence:[ref("NVE",evidence.evidenceDigest)],acceptanceCriterionIds:["AC-DEV-WIV-TRACEABILITY-001"],authority:"approved",scope:"work-item-verification/approved"},"traceabilityDigest");
  return {policyArtifact,subject,obligations,binding,invocation,raw,evidence,evaluation,candidate,gateApproval,candidateTrace,approvedTrace};
}
function loaded(value) { const bytes=Buffer.from(canonicalJson(value)); const id=value.traceabilityDigest?`TRACE-${value.kind}`:value.approvalId??value.normalizedEvidenceId??value.candidateId??value.subjectId??value.evaluationId??value.bindingId??value.obligationSetId??value.verificationAttemptId??value.policyId??value.id; return {value,bytes,ref:{artifactId:id,digest:sha256Digest(bytes),schema:"https://devrelay.dev/test/v1",mediaType:"application/json",uri:`memory://${id}`}}; }
function context(traceKind="candidateTrace", mutate=(x)=>x) { const f=fixture(); f[traceKind]=mutate(f[traceKind],f)??f[traceKind]; delete f[traceKind==="candidateTrace"?"approvedTrace":"candidateTrace"]; const entries=Object.fromEntries(Object.entries(f).map(([name,value])=>[name,[loaded(value)]])); return { invocation:{module:{id:"work-item-verification",version:"0.1.0",operation:"verify-work-item"}}, moduleResult:{status:"completed",outcome:"verified"}, loadedInputs:entries, loadedOutputs:{} }; }
function seedContributor(id,scope,authority,kind,stableId) { return {metadata:{id,version:"1.0.0"},authority,scope,ownership:{authority,scope,nodeKinds:[kind],edgeKinds:[]},match:({invocation})=>invocation.module.id===id,project:({loadedOutputs})=>({horizon:"verification",nodes:[{kind,stableId,label:stableId,attributes:{},sourceLocators:[{artifact:{artifactId:loadedOutputs.seed[0].ref.artifactId,digest:loadedOutputs.seed[0].ref.digest},jsonPointer:"",entityDigest:canonicalJsonDigest(loadedOutputs.seed[0].value)}]}],edges:[]})}; }

test("candidate projection is deterministic and never claims verification, approval, integration, completion, or inverse facts", async()=>{const ctx=context();const first=await workItemVerificationCandidateTraceabilityContributor.project(ctx),second=await workItemVerificationCandidateTraceabilityContributor.project(ctx);assert.deepEqual(first,second);assert.ok(first.nodes.some(({kind})=>kind==="verification-evidence"));assert.deepEqual(first.edges,[]);assert.equal(canonicalJson(first).match(/verified-by|integrat|completion|approved-by/g),null)});
test("approved projection requires exact candidate, evidence, criteria, work item, and approval-bound trace",async()=>{const projection=await workItemVerificationApprovedTraceabilityContributor.project(context("approvedTrace"));assert.equal(projection.edges.filter(({kind})=>kind==="verified-by").length,3);for(const mutate of [(trace)=>seal({...trace,candidate:ref("STALE",trace.candidate.digest)},"traceabilityDigest"),(trace)=>seal({...trace,acceptedEvidence:[ref("OTHER")]},"traceabilityDigest"),(trace)=>seal({...trace,acceptanceCriterionIds:["AC-MISSING"]},"traceabilityDigest"),(trace)=>seal({...trace,gateApproval:ref("OTHER")},"traceabilityDigest")])await assert.rejects(workItemVerificationApprovedTraceabilityContributor.project(context("approvedTrace",mutate)))});
test("a fully resealed forged trace ref cannot replace a loaded authoritative Gate approval",async()=>{const forged=context("approvedTrace",(trace)=>seal({...trace,gateApproval:ref("OTHER")},"traceabilityDigest"));await assert.rejects(workItemVerificationApprovedTraceabilityContributor.project(forged));const missing=context("approvedTrace");delete missing.loadedInputs.gateApproval;await assert.rejects(workItemVerificationApprovedTraceabilityContributor.project(missing));const duplicate=context("approvedTrace");duplicate.loadedInputs.duplicateApproval=duplicate.loadedInputs.gateApproval;await assert.rejects(workItemVerificationApprovedTraceabilityContributor.project(duplicate))});
test("approved projection rejects malformed raw bytes and outer approval identity substitution",async()=>{const bytes=context("approvedTrace");bytes.loadedInputs.gateApproval[0].bytes=Buffer.from("{}");await assert.rejects(workItemVerificationApprovedTraceabilityContributor.project(bytes));const identity=context("approvedTrace");identity.loadedInputs.gateApproval[0].ref={...identity.loadedInputs.gateApproval[0].ref,artifactId:"OTHER"};await assert.rejects(workItemVerificationApprovedTraceabilityContributor.project(identity));const digest=context("approvedTrace");digest.loadedInputs.gateApproval[0].ref={...digest.loadedInputs.gateApproval[0].ref,digest:D};await assert.rejects(workItemVerificationApprovedTraceabilityContributor.project(digest))});
test("approved contributor rejects non-verified candidates and missing subject references",async()=>{await assert.rejects(workItemVerificationApprovedTraceabilityContributor.project(context("approvedTrace",(_trace,f)=>{f.candidate=seal({...f.candidate,outcome:"failed"},"candidateDigest");return _trace})));await assert.rejects(workItemVerificationApprovedTraceabilityContributor.project(context("approvedTrace",(trace,f)=>{f.subject=seal({...f.subject,workItemId:""},"subjectDigest");return trace})))});
test("candidate and approved updates merge atomically, replay identically, and support forward lifecycle queries",async()=>{const req=seedContributor("seed-req","requirements/baseline","approved","acceptance-criterion","AC-DEV-WIV-TRACEABILITY-001"),work=seedContributor("seed-work","work-breakdown/candidate","candidate","work-item","WI-WIV-TRACEABILITY");const service=createTraceabilityGraphService({graphId:"wiv",projectId:"devrelay",store:createInMemoryTraceabilityStore(),contributors:[req,work,workItemVerificationCandidateTraceabilityContributor,workItemVerificationApprovedTraceabilityContributor]});const prepare=async(ctx,id)=>service.prepare({baseGraph:service.captureBase(),invocation:{invocationId:id,...ctx.invocation},invocationFingerprint:canonicalJsonDigest({id}),moduleResult:{invocationId:id,...ctx.moduleResult,outputs:{},evidence:[]},loadedInputs:ctx.loadedInputs,loadedOutputs:{}});for(const id of ["seed-req","seed-work"]){const invocation={invocationId:id,module:{id,version:"1",operation:"seed"}},seed=loaded({apiVersion:"devrelay.dev/v1alpha1",kind:"Seed",id});const p=await service.prepare({baseGraph:service.captureBase(),invocation,invocationFingerprint:canonicalJsonDigest(invocation),moduleResult:{invocationId:id,status:"completed",outcome:"seeded",outputs:{seed:[seed.ref]},evidence:[]},loadedOutputs:{seed:[seed]}});await service.mergePrepared(p)}let p=await prepare(context(),"candidate");const duplicate=await prepare(context(),"candidate-replay");assert.deepEqual(p.update.nodeChanges,duplicate.update.nodeChanges);assert.deepEqual(p.update.edgeChanges,duplicate.update.edgeChanges);await service.mergePrepared(p);p=await prepare(context("approvedTrace"),"approved");const merged=await service.mergePrepared(p);assert.ok(merged.receipt.resultGraph.digest);const byId=new Map(merged.snapshot.nodes.map((node)=>[node.nodeId,node]));for(const source of ["AC-DEV-WIV-TRACEABILITY-001","WI-WIV-TRACEABILITY"])assert.ok(merged.snapshot.edges.some((edge)=>edge.kind==="verified-by"&&byId.get(edge.sourceNodeId)?.stableId===source&&byId.get(edge.targetNodeId)?.stableId==="EV-AC"))});
